// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.oci.OsManagementHub.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.oci.OsManagementHub.outputs.LifecycleEnvironmentStageManagedInstanceId;
import com.pulumi.oci.OsManagementHub.outputs.LifecycleEnvironmentStageSoftwareSourceId;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class LifecycleEnvironmentStage {
    /**
     * @return The CPU architecture of the managed instances in the lifecycle environment.
     * 
     */
    private @Nullable String archType;
    /**
     * @return (Updatable) The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment that contains the lifecycle stage.
     * 
     */
    private @Nullable String compartmentId;
    /**
     * @return (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see [Resource Tags](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm). Example: `{&#34;Operations.CostCenter&#34;: &#34;42&#34;}`
     * 
     */
    private @Nullable Map<String,String> definedTags;
    /**
     * @return (Updatable) A user-friendly name for the lifecycle stage. Does not have to be unique and you can change the name later. Avoid entering confidential information.
     * 
     */
    private String displayName;
    /**
     * @return (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see [Resource Tags](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm). Example: `{&#34;Department&#34;: &#34;Finance&#34;}`
     * 
     */
    private @Nullable Map<String,String> freeformTags;
    /**
     * @return The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the software source.
     * 
     */
    private @Nullable String id;
    /**
     * @return The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the lifecycle environment that contains the lifecycle stage.
     * 
     */
    private @Nullable String lifecycleEnvironmentId;
    /**
     * @return The location of managed instances attached to the lifecycle environment. If no location is provided, the default is &#39;ON_PREMISE.&#39;
     * 
     */
    private @Nullable String location;
    /**
     * @return The list of managed instances associated with the lifecycle stage.
     * 
     */
    private @Nullable List<LifecycleEnvironmentStageManagedInstanceId> managedInstanceIds;
    /**
     * @return The operating system of the managed instances in the lifecycle environment.
     * 
     */
    private @Nullable String osFamily;
    /**
     * @return User-specified rank for the lifecycle stage. Rank determines the hierarchy of the lifecycle stages within the lifecycle environment.
     * 
     */
    private Integer rank;
    /**
     * @return Provides identifying information for the specified software source.
     * 
     */
    private @Nullable List<LifecycleEnvironmentStageSoftwareSourceId> softwareSourceIds;
    /**
     * @return The current state of the lifecycle environment.
     * 
     */
    private @Nullable String state;
    /**
     * @return System tags for this resource. Each key is predefined and scoped to a namespace. Example: `{&#34;orcl-cloud.free-tier-retained&#34;: &#34;true&#34;}`
     * 
     */
    private @Nullable Map<String,String> systemTags;
    /**
     * @return The time the lifecycle environment was created (in [RFC 3339](https://tools.ietf.org/rfc/rfc3339) format).
     * 
     */
    private @Nullable String timeCreated;
    /**
     * @return The time the lifecycle environment was last modified (in [RFC 3339](https://tools.ietf.org/rfc/rfc3339) format).
     * 
     */
    private @Nullable String timeModified;
    /**
     * @return The vendor of the operating system used by the managed instances in the lifecycle environment.
     * 
     * ** IMPORTANT **
     * Any change to a property that does not support update will force the destruction and recreation of the resource with the new property values
     * 
     */
    private @Nullable String vendorName;

    private LifecycleEnvironmentStage() {}
    /**
     * @return The CPU architecture of the managed instances in the lifecycle environment.
     * 
     */
    public Optional<String> archType() {
        return Optional.ofNullable(this.archType);
    }
    /**
     * @return (Updatable) The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment that contains the lifecycle stage.
     * 
     */
    public Optional<String> compartmentId() {
        return Optional.ofNullable(this.compartmentId);
    }
    /**
     * @return (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see [Resource Tags](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm). Example: `{&#34;Operations.CostCenter&#34;: &#34;42&#34;}`
     * 
     */
    public Map<String,String> definedTags() {
        return this.definedTags == null ? Map.of() : this.definedTags;
    }
    /**
     * @return (Updatable) A user-friendly name for the lifecycle stage. Does not have to be unique and you can change the name later. Avoid entering confidential information.
     * 
     */
    public String displayName() {
        return this.displayName;
    }
    /**
     * @return (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see [Resource Tags](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm). Example: `{&#34;Department&#34;: &#34;Finance&#34;}`
     * 
     */
    public Map<String,String> freeformTags() {
        return this.freeformTags == null ? Map.of() : this.freeformTags;
    }
    /**
     * @return The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the software source.
     * 
     */
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }
    /**
     * @return The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the lifecycle environment that contains the lifecycle stage.
     * 
     */
    public Optional<String> lifecycleEnvironmentId() {
        return Optional.ofNullable(this.lifecycleEnvironmentId);
    }
    /**
     * @return The location of managed instances attached to the lifecycle environment. If no location is provided, the default is &#39;ON_PREMISE.&#39;
     * 
     */
    public Optional<String> location() {
        return Optional.ofNullable(this.location);
    }
    /**
     * @return The list of managed instances associated with the lifecycle stage.
     * 
     */
    public List<LifecycleEnvironmentStageManagedInstanceId> managedInstanceIds() {
        return this.managedInstanceIds == null ? List.of() : this.managedInstanceIds;
    }
    /**
     * @return The operating system of the managed instances in the lifecycle environment.
     * 
     */
    public Optional<String> osFamily() {
        return Optional.ofNullable(this.osFamily);
    }
    /**
     * @return User-specified rank for the lifecycle stage. Rank determines the hierarchy of the lifecycle stages within the lifecycle environment.
     * 
     */
    public Integer rank() {
        return this.rank;
    }
    /**
     * @return Provides identifying information for the specified software source.
     * 
     */
    public List<LifecycleEnvironmentStageSoftwareSourceId> softwareSourceIds() {
        return this.softwareSourceIds == null ? List.of() : this.softwareSourceIds;
    }
    /**
     * @return The current state of the lifecycle environment.
     * 
     */
    public Optional<String> state() {
        return Optional.ofNullable(this.state);
    }
    /**
     * @return System tags for this resource. Each key is predefined and scoped to a namespace. Example: `{&#34;orcl-cloud.free-tier-retained&#34;: &#34;true&#34;}`
     * 
     */
    public Map<String,String> systemTags() {
        return this.systemTags == null ? Map.of() : this.systemTags;
    }
    /**
     * @return The time the lifecycle environment was created (in [RFC 3339](https://tools.ietf.org/rfc/rfc3339) format).
     * 
     */
    public Optional<String> timeCreated() {
        return Optional.ofNullable(this.timeCreated);
    }
    /**
     * @return The time the lifecycle environment was last modified (in [RFC 3339](https://tools.ietf.org/rfc/rfc3339) format).
     * 
     */
    public Optional<String> timeModified() {
        return Optional.ofNullable(this.timeModified);
    }
    /**
     * @return The vendor of the operating system used by the managed instances in the lifecycle environment.
     * 
     * ** IMPORTANT **
     * Any change to a property that does not support update will force the destruction and recreation of the resource with the new property values
     * 
     */
    public Optional<String> vendorName() {
        return Optional.ofNullable(this.vendorName);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(LifecycleEnvironmentStage defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String archType;
        private @Nullable String compartmentId;
        private @Nullable Map<String,String> definedTags;
        private String displayName;
        private @Nullable Map<String,String> freeformTags;
        private @Nullable String id;
        private @Nullable String lifecycleEnvironmentId;
        private @Nullable String location;
        private @Nullable List<LifecycleEnvironmentStageManagedInstanceId> managedInstanceIds;
        private @Nullable String osFamily;
        private Integer rank;
        private @Nullable List<LifecycleEnvironmentStageSoftwareSourceId> softwareSourceIds;
        private @Nullable String state;
        private @Nullable Map<String,String> systemTags;
        private @Nullable String timeCreated;
        private @Nullable String timeModified;
        private @Nullable String vendorName;
        public Builder() {}
        public Builder(LifecycleEnvironmentStage defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.archType = defaults.archType;
    	      this.compartmentId = defaults.compartmentId;
    	      this.definedTags = defaults.definedTags;
    	      this.displayName = defaults.displayName;
    	      this.freeformTags = defaults.freeformTags;
    	      this.id = defaults.id;
    	      this.lifecycleEnvironmentId = defaults.lifecycleEnvironmentId;
    	      this.location = defaults.location;
    	      this.managedInstanceIds = defaults.managedInstanceIds;
    	      this.osFamily = defaults.osFamily;
    	      this.rank = defaults.rank;
    	      this.softwareSourceIds = defaults.softwareSourceIds;
    	      this.state = defaults.state;
    	      this.systemTags = defaults.systemTags;
    	      this.timeCreated = defaults.timeCreated;
    	      this.timeModified = defaults.timeModified;
    	      this.vendorName = defaults.vendorName;
        }

        @CustomType.Setter
        public Builder archType(@Nullable String archType) {

            this.archType = archType;
            return this;
        }
        @CustomType.Setter
        public Builder compartmentId(@Nullable String compartmentId) {

            this.compartmentId = compartmentId;
            return this;
        }
        @CustomType.Setter
        public Builder definedTags(@Nullable Map<String,String> definedTags) {

            this.definedTags = definedTags;
            return this;
        }
        @CustomType.Setter
        public Builder displayName(String displayName) {
            if (displayName == null) {
              throw new MissingRequiredPropertyException("LifecycleEnvironmentStage", "displayName");
            }
            this.displayName = displayName;
            return this;
        }
        @CustomType.Setter
        public Builder freeformTags(@Nullable Map<String,String> freeformTags) {

            this.freeformTags = freeformTags;
            return this;
        }
        @CustomType.Setter
        public Builder id(@Nullable String id) {

            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder lifecycleEnvironmentId(@Nullable String lifecycleEnvironmentId) {

            this.lifecycleEnvironmentId = lifecycleEnvironmentId;
            return this;
        }
        @CustomType.Setter
        public Builder location(@Nullable String location) {

            this.location = location;
            return this;
        }
        @CustomType.Setter
        public Builder managedInstanceIds(@Nullable List<LifecycleEnvironmentStageManagedInstanceId> managedInstanceIds) {

            this.managedInstanceIds = managedInstanceIds;
            return this;
        }
        public Builder managedInstanceIds(LifecycleEnvironmentStageManagedInstanceId... managedInstanceIds) {
            return managedInstanceIds(List.of(managedInstanceIds));
        }
        @CustomType.Setter
        public Builder osFamily(@Nullable String osFamily) {

            this.osFamily = osFamily;
            return this;
        }
        @CustomType.Setter
        public Builder rank(Integer rank) {
            if (rank == null) {
              throw new MissingRequiredPropertyException("LifecycleEnvironmentStage", "rank");
            }
            this.rank = rank;
            return this;
        }
        @CustomType.Setter
        public Builder softwareSourceIds(@Nullable List<LifecycleEnvironmentStageSoftwareSourceId> softwareSourceIds) {

            this.softwareSourceIds = softwareSourceIds;
            return this;
        }
        public Builder softwareSourceIds(LifecycleEnvironmentStageSoftwareSourceId... softwareSourceIds) {
            return softwareSourceIds(List.of(softwareSourceIds));
        }
        @CustomType.Setter
        public Builder state(@Nullable String state) {

            this.state = state;
            return this;
        }
        @CustomType.Setter
        public Builder systemTags(@Nullable Map<String,String> systemTags) {

            this.systemTags = systemTags;
            return this;
        }
        @CustomType.Setter
        public Builder timeCreated(@Nullable String timeCreated) {

            this.timeCreated = timeCreated;
            return this;
        }
        @CustomType.Setter
        public Builder timeModified(@Nullable String timeModified) {

            this.timeModified = timeModified;
            return this;
        }
        @CustomType.Setter
        public Builder vendorName(@Nullable String vendorName) {

            this.vendorName = vendorName;
            return this;
        }
        public LifecycleEnvironmentStage build() {
            final var _resultValue = new LifecycleEnvironmentStage();
            _resultValue.archType = archType;
            _resultValue.compartmentId = compartmentId;
            _resultValue.definedTags = definedTags;
            _resultValue.displayName = displayName;
            _resultValue.freeformTags = freeformTags;
            _resultValue.id = id;
            _resultValue.lifecycleEnvironmentId = lifecycleEnvironmentId;
            _resultValue.location = location;
            _resultValue.managedInstanceIds = managedInstanceIds;
            _resultValue.osFamily = osFamily;
            _resultValue.rank = rank;
            _resultValue.softwareSourceIds = softwareSourceIds;
            _resultValue.state = state;
            _resultValue.systemTags = systemTags;
            _resultValue.timeCreated = timeCreated;
            _resultValue.timeModified = timeModified;
            _resultValue.vendorName = vendorName;
            return _resultValue;
        }
    }
}
