// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.oci.ApmSynthetics.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetMonitorsMonitorCollectionItemConfigurationClientCertificateDetailPrivateKey {
    /**
     * @return Content of the private key file.
     * 
     */
    private String content;
    /**
     * @return Name of the private key file.
     * 
     */
    private String fileName;

    private GetMonitorsMonitorCollectionItemConfigurationClientCertificateDetailPrivateKey() {}
    /**
     * @return Content of the private key file.
     * 
     */
    public String content() {
        return this.content;
    }
    /**
     * @return Name of the private key file.
     * 
     */
    public String fileName() {
        return this.fileName;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetMonitorsMonitorCollectionItemConfigurationClientCertificateDetailPrivateKey defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String content;
        private String fileName;
        public Builder() {}
        public Builder(GetMonitorsMonitorCollectionItemConfigurationClientCertificateDetailPrivateKey defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.content = defaults.content;
    	      this.fileName = defaults.fileName;
        }

        @CustomType.Setter
        public Builder content(String content) {
            if (content == null) {
              throw new MissingRequiredPropertyException("GetMonitorsMonitorCollectionItemConfigurationClientCertificateDetailPrivateKey", "content");
            }
            this.content = content;
            return this;
        }
        @CustomType.Setter
        public Builder fileName(String fileName) {
            if (fileName == null) {
              throw new MissingRequiredPropertyException("GetMonitorsMonitorCollectionItemConfigurationClientCertificateDetailPrivateKey", "fileName");
            }
            this.fileName = fileName;
            return this;
        }
        public GetMonitorsMonitorCollectionItemConfigurationClientCertificateDetailPrivateKey build() {
            final var _resultValue = new GetMonitorsMonitorCollectionItemConfigurationClientCertificateDetailPrivateKey();
            _resultValue.content = content;
            _resultValue.fileName = fileName;
            return _resultValue;
        }
    }
}
