// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Oci.Oci
{
    public static class GetWlmsManagedInstanceServers
    {
        /// <summary>
        /// This data source provides the list of Managed Instance Servers in Oracle Cloud Infrastructure Wlms service.
        /// 
        /// Gets list of servers in a specific managed instance.
        /// 
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Oci = Pulumi.Oci;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var testManagedInstanceServers = Oci.Oci.GetWlmsManagedInstanceServers.Invoke(new()
        ///     {
        ///         ManagedInstanceId = testManagedInstance.Id,
        ///         Name = managedInstanceServerName,
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetWlmsManagedInstanceServersResult> InvokeAsync(GetWlmsManagedInstanceServersArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetWlmsManagedInstanceServersResult>("oci:oci/getWlmsManagedInstanceServers:getWlmsManagedInstanceServers", args ?? new GetWlmsManagedInstanceServersArgs(), options.WithDefaults());

        /// <summary>
        /// This data source provides the list of Managed Instance Servers in Oracle Cloud Infrastructure Wlms service.
        /// 
        /// Gets list of servers in a specific managed instance.
        /// 
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Oci = Pulumi.Oci;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var testManagedInstanceServers = Oci.Oci.GetWlmsManagedInstanceServers.Invoke(new()
        ///     {
        ///         ManagedInstanceId = testManagedInstance.Id,
        ///         Name = managedInstanceServerName,
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetWlmsManagedInstanceServersResult> Invoke(GetWlmsManagedInstanceServersInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetWlmsManagedInstanceServersResult>("oci:oci/getWlmsManagedInstanceServers:getWlmsManagedInstanceServers", args ?? new GetWlmsManagedInstanceServersInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// This data source provides the list of Managed Instance Servers in Oracle Cloud Infrastructure Wlms service.
        /// 
        /// Gets list of servers in a specific managed instance.
        /// 
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Oci = Pulumi.Oci;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var testManagedInstanceServers = Oci.Oci.GetWlmsManagedInstanceServers.Invoke(new()
        ///     {
        ///         ManagedInstanceId = testManagedInstance.Id,
        ///         Name = managedInstanceServerName,
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetWlmsManagedInstanceServersResult> Invoke(GetWlmsManagedInstanceServersInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetWlmsManagedInstanceServersResult>("oci:oci/getWlmsManagedInstanceServers:getWlmsManagedInstanceServers", args ?? new GetWlmsManagedInstanceServersInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetWlmsManagedInstanceServersArgs : global::Pulumi.InvokeArgs
    {
        [Input("filters")]
        private List<Inputs.GetWlmsManagedInstanceServersFilterArgs>? _filters;
        public List<Inputs.GetWlmsManagedInstanceServersFilterArgs> Filters
        {
            get => _filters ?? (_filters = new List<Inputs.GetWlmsManagedInstanceServersFilterArgs>());
            set => _filters = value;
        }

        /// <summary>
        /// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the instance.
        /// </summary>
        [Input("managedInstanceId", required: true)]
        public string ManagedInstanceId { get; set; } = null!;

        /// <summary>
        /// The name of the resource.
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        public GetWlmsManagedInstanceServersArgs()
        {
        }
        public static new GetWlmsManagedInstanceServersArgs Empty => new GetWlmsManagedInstanceServersArgs();
    }

    public sealed class GetWlmsManagedInstanceServersInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("filters")]
        private InputList<Inputs.GetWlmsManagedInstanceServersFilterInputArgs>? _filters;
        public InputList<Inputs.GetWlmsManagedInstanceServersFilterInputArgs> Filters
        {
            get => _filters ?? (_filters = new InputList<Inputs.GetWlmsManagedInstanceServersFilterInputArgs>());
            set => _filters = value;
        }

        /// <summary>
        /// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the instance.
        /// </summary>
        [Input("managedInstanceId", required: true)]
        public Input<string> ManagedInstanceId { get; set; } = null!;

        /// <summary>
        /// The name of the resource.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public GetWlmsManagedInstanceServersInvokeArgs()
        {
        }
        public static new GetWlmsManagedInstanceServersInvokeArgs Empty => new GetWlmsManagedInstanceServersInvokeArgs();
    }


    [OutputType]
    public sealed class GetWlmsManagedInstanceServersResult
    {
        public readonly ImmutableArray<Outputs.GetWlmsManagedInstanceServersFilterResult> Filters;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The managed instance ID of the server.
        /// </summary>
        public readonly string ManagedInstanceId;
        /// <summary>
        /// The name of the server.
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// The list of server_collection.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetWlmsManagedInstanceServersServerCollectionResult> ServerCollections;

        [OutputConstructor]
        private GetWlmsManagedInstanceServersResult(
            ImmutableArray<Outputs.GetWlmsManagedInstanceServersFilterResult> filters,

            string id,

            string managedInstanceId,

            string? name,

            ImmutableArray<Outputs.GetWlmsManagedInstanceServersServerCollectionResult> serverCollections)
        {
            Filters = filters;
            Id = id;
            ManagedInstanceId = managedInstanceId;
            Name = name;
            ServerCollections = serverCollections;
        }
    }
}
