provider: oci
major-version: 3
providerDefaultBranch: main
parallel: 1
timeout: 90
esc:
    enabled: true
    environment: imports/github-secrets # No repo-specific secrets.
env:
    TF_VAR_tenancy_ocid: ${{ secrets.TF_VAR_tenancy_ocid }}
    TF_VAR_user_ocid: ${{ secrets.TF_VAR_user_ocid }}
    TF_VAR_private_key: ${{ secrets.TF_VAR_private_key }}
    TF_VAR_region: ${{ secrets.TF_VAR_region }}
makeTemplate: bridged
plugins:
    - name: std
      version: "1.6.2"
    - name: terraform
      version: "1.0.16"
      kind: converter
    - name: tls
      version: "4.1.0"
    - name: github
      version: "4.10.0"
    - name: kubernetes
      version: "3.17.0"
    - name: random
      version: "4.4.1"
goBuildParallelism: 1
license:
    ignore:
        - github.com/oracle/terraform-provider-oci/shim
pulumiConvert: 1
