provider: oci
major-version: 4
providerDefaultBranch: main
parallel: 1
timeout: 90
esc:
  enabled: true
  environment: imports/github-secrets # No repo-specific secrets.
env:
  TF_VAR_tenancy_ocid: ${{ secrets.TF_VAR_tenancy_ocid }}
  TF_VAR_user_ocid: ${{ secrets.TF_VAR_user_ocid }}
  TF_VAR_private_key: ${{ secrets.TF_VAR_private_key }}
  TF_VAR_region: ${{ secrets.TF_VAR_region }}
makeTemplate: bridged
goBuildParallelism: 1
freeDiskSpaceBeforeSdkBuild: true
license:
  ignore:
    - github.com/oracle/terraform-provider-oci/shim
pulumiConvert: 1
