provider: oci
major-version: 1
lint: false
providerDefaultBranch: main
parallel: 1
timeout: 90
env:
  TF_VAR_tenancy_ocid: ${{ secrets.TF_VAR_tenancy_ocid }}
  TF_VAR_user_ocid: ${{ secrets.TF_VAR_user_ocid }}
  TF_VAR_private_key: ${{ secrets.TF_VAR_private_key }}
  TF_VAR_region: ${{ secrets.TF_VAR_region }}
makeTemplate: bridged
plugins:
  - name: tls
    version: "4.1.0"
  - name: github
    version: "4.10.0"
  - name: kubernetes
    version: "3.17.0"
  - name: random
    version: "4.4.1"
team: ecosystem
goBuildParallelism: 1
runner:
  publish: pulumi-ubuntu-8core
  buildSdk: pulumi-ubuntu-8core
javaGenVersion: "v0.9.5"
