// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Oci.FleetAppsManagement.Inputs
{

    public sealed class FleetNotificationPreferencesPreferencesArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// (Updatable) Enables or disables notification on Job Failures.
        /// </summary>
        [Input("onJobFailure")]
        public Input<bool>? OnJobFailure { get; set; }

        /// <summary>
        /// (Updatable) Enables or disables notification on Environment Fleet Topology Modification.
        /// </summary>
        [Input("onTopologyModification")]
        public Input<bool>? OnTopologyModification { get; set; }

        /// <summary>
        /// (Updatable) Enables notification on upcoming schedule.
        /// </summary>
        [Input("onUpcomingSchedule")]
        public Input<bool>? OnUpcomingSchedule { get; set; }

        public FleetNotificationPreferencesPreferencesArgs()
        {
        }
        public static new FleetNotificationPreferencesPreferencesArgs Empty => new FleetNotificationPreferencesPreferencesArgs();
    }
}
