// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package datacatalog

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This data source provides details about a specific Catalog resource in Oracle Cloud Infrastructure Data Catalog service.
//
// Gets a data catalog by identifier.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-oci/sdk/go/oci/DataCatalog"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := DataCatalog.GetCatalog(ctx, &datacatalog.GetCatalogArgs{
// 			CatalogId: oci_datacatalog_catalog.Test_catalog.Id,
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func LookupCatalog(ctx *pulumi.Context, args *LookupCatalogArgs, opts ...pulumi.InvokeOption) (*LookupCatalogResult, error) {
	var rv LookupCatalogResult
	err := ctx.Invoke("oci:DataCatalog/getCatalog:getCatalog", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getCatalog.
type LookupCatalogArgs struct {
	// Unique catalog identifier.
	CatalogId string `pulumi:"catalogId"`
}

// A collection of values returned by getCatalog.
type LookupCatalogResult struct {
	// The list of private reverse connection endpoints attached to the catalog
	AttachedCatalogPrivateEndpoints []string `pulumi:"attachedCatalogPrivateEndpoints"`
	CatalogId                       string   `pulumi:"catalogId"`
	// Compartment identifier.
	CompartmentId string `pulumi:"compartmentId"`
	// Usage of predefined tag keys. These predefined keys are scoped to namespaces. Example: `{"foo-namespace.bar-key": "value"}`
	DefinedTags map[string]interface{} `pulumi:"definedTags"`
	// Data catalog identifier, which can be renamed.
	DisplayName string `pulumi:"displayName"`
	// Simple key-value pair that is applied without any predefined name, type, or scope. Exists for cross-compatibility only. Example: `{"bar-key": "value"}`
	FreeformTags map[string]interface{} `pulumi:"freeformTags"`
	// Unique identifier that is immutable on creation.
	Id string `pulumi:"id"`
	// An message describing the current state in more detail. For example, it can be used to provide actionable information for a resource in 'Failed' state.
	LifecycleDetails string `pulumi:"lifecycleDetails"`
	// The number of data objects added to the data catalog. Please see the data catalog documentation for further information on how this is calculated.
	NumberOfObjects int `pulumi:"numberOfObjects"`
	// The REST front endpoint URL to the data catalog instance.
	ServiceApiUrl string `pulumi:"serviceApiUrl"`
	// The console front endpoint URL to the data catalog instance.
	ServiceConsoleUrl string `pulumi:"serviceConsoleUrl"`
	// The current state of the data catalog resource.
	State string `pulumi:"state"`
	// The time the data catalog was created. An [RFC3339](https://tools.ietf.org/html/rfc3339) formatted datetime string.
	TimeCreated string `pulumi:"timeCreated"`
	// The time the data catalog was updated. An [RFC3339](https://tools.ietf.org/html/rfc3339) formatted datetime string.
	TimeUpdated string `pulumi:"timeUpdated"`
}

func LookupCatalogOutput(ctx *pulumi.Context, args LookupCatalogOutputArgs, opts ...pulumi.InvokeOption) LookupCatalogResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupCatalogResult, error) {
			args := v.(LookupCatalogArgs)
			r, err := LookupCatalog(ctx, &args, opts...)
			var s LookupCatalogResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupCatalogResultOutput)
}

// A collection of arguments for invoking getCatalog.
type LookupCatalogOutputArgs struct {
	// Unique catalog identifier.
	CatalogId pulumi.StringInput `pulumi:"catalogId"`
}

func (LookupCatalogOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCatalogArgs)(nil)).Elem()
}

// A collection of values returned by getCatalog.
type LookupCatalogResultOutput struct{ *pulumi.OutputState }

func (LookupCatalogResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCatalogResult)(nil)).Elem()
}

func (o LookupCatalogResultOutput) ToLookupCatalogResultOutput() LookupCatalogResultOutput {
	return o
}

func (o LookupCatalogResultOutput) ToLookupCatalogResultOutputWithContext(ctx context.Context) LookupCatalogResultOutput {
	return o
}

// The list of private reverse connection endpoints attached to the catalog
func (o LookupCatalogResultOutput) AttachedCatalogPrivateEndpoints() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupCatalogResult) []string { return v.AttachedCatalogPrivateEndpoints }).(pulumi.StringArrayOutput)
}

func (o LookupCatalogResultOutput) CatalogId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCatalogResult) string { return v.CatalogId }).(pulumi.StringOutput)
}

// Compartment identifier.
func (o LookupCatalogResultOutput) CompartmentId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCatalogResult) string { return v.CompartmentId }).(pulumi.StringOutput)
}

// Usage of predefined tag keys. These predefined keys are scoped to namespaces. Example: `{"foo-namespace.bar-key": "value"}`
func (o LookupCatalogResultOutput) DefinedTags() pulumi.MapOutput {
	return o.ApplyT(func(v LookupCatalogResult) map[string]interface{} { return v.DefinedTags }).(pulumi.MapOutput)
}

// Data catalog identifier, which can be renamed.
func (o LookupCatalogResultOutput) DisplayName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCatalogResult) string { return v.DisplayName }).(pulumi.StringOutput)
}

// Simple key-value pair that is applied without any predefined name, type, or scope. Exists for cross-compatibility only. Example: `{"bar-key": "value"}`
func (o LookupCatalogResultOutput) FreeformTags() pulumi.MapOutput {
	return o.ApplyT(func(v LookupCatalogResult) map[string]interface{} { return v.FreeformTags }).(pulumi.MapOutput)
}

// Unique identifier that is immutable on creation.
func (o LookupCatalogResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCatalogResult) string { return v.Id }).(pulumi.StringOutput)
}

// An message describing the current state in more detail. For example, it can be used to provide actionable information for a resource in 'Failed' state.
func (o LookupCatalogResultOutput) LifecycleDetails() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCatalogResult) string { return v.LifecycleDetails }).(pulumi.StringOutput)
}

// The number of data objects added to the data catalog. Please see the data catalog documentation for further information on how this is calculated.
func (o LookupCatalogResultOutput) NumberOfObjects() pulumi.IntOutput {
	return o.ApplyT(func(v LookupCatalogResult) int { return v.NumberOfObjects }).(pulumi.IntOutput)
}

// The REST front endpoint URL to the data catalog instance.
func (o LookupCatalogResultOutput) ServiceApiUrl() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCatalogResult) string { return v.ServiceApiUrl }).(pulumi.StringOutput)
}

// The console front endpoint URL to the data catalog instance.
func (o LookupCatalogResultOutput) ServiceConsoleUrl() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCatalogResult) string { return v.ServiceConsoleUrl }).(pulumi.StringOutput)
}

// The current state of the data catalog resource.
func (o LookupCatalogResultOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCatalogResult) string { return v.State }).(pulumi.StringOutput)
}

// The time the data catalog was created. An [RFC3339](https://tools.ietf.org/html/rfc3339) formatted datetime string.
func (o LookupCatalogResultOutput) TimeCreated() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCatalogResult) string { return v.TimeCreated }).(pulumi.StringOutput)
}

// The time the data catalog was updated. An [RFC3339](https://tools.ietf.org/html/rfc3339) formatted datetime string.
func (o LookupCatalogResultOutput) TimeUpdated() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCatalogResult) string { return v.TimeUpdated }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupCatalogResultOutput{})
}
