// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.oci.DatabaseManagement.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetCloudDbSystemArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetCloudDbSystemArgs Empty = new GetCloudDbSystemArgs();

    /**
     * The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the cloud DB system.
     * 
     */
    @Import(name="cloudDbSystemId", required=true)
    private Output<String> cloudDbSystemId;

    /**
     * @return The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the cloud DB system.
     * 
     */
    public Output<String> cloudDbSystemId() {
        return this.cloudDbSystemId;
    }

    private GetCloudDbSystemArgs() {}

    private GetCloudDbSystemArgs(GetCloudDbSystemArgs $) {
        this.cloudDbSystemId = $.cloudDbSystemId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetCloudDbSystemArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetCloudDbSystemArgs $;

        public Builder() {
            $ = new GetCloudDbSystemArgs();
        }

        public Builder(GetCloudDbSystemArgs defaults) {
            $ = new GetCloudDbSystemArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param cloudDbSystemId The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the cloud DB system.
         * 
         * @return builder
         * 
         */
        public Builder cloudDbSystemId(Output<String> cloudDbSystemId) {
            $.cloudDbSystemId = cloudDbSystemId;
            return this;
        }

        /**
         * @param cloudDbSystemId The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the cloud DB system.
         * 
         * @return builder
         * 
         */
        public Builder cloudDbSystemId(String cloudDbSystemId) {
            return cloudDbSystemId(Output.of(cloudDbSystemId));
        }

        public GetCloudDbSystemArgs build() {
            if ($.cloudDbSystemId == null) {
                throw new MissingRequiredPropertyException("GetCloudDbSystemArgs", "cloudDbSystemId");
            }
            return $;
        }
    }

}
