// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Oci.FleetAppsManagement.Outputs
{

    [OutputType]
    public sealed class GetSchedulerDefinitionRunBookInputParameterResult
    {
        /// <summary>
        /// Arguments for the Task
        /// </summary>
        public readonly ImmutableArray<Outputs.GetSchedulerDefinitionRunBookInputParameterArgumentResult> Arguments;
        /// <summary>
        /// stepName for which the input parameters are provided
        /// </summary>
        public readonly string StepName;

        [OutputConstructor]
        private GetSchedulerDefinitionRunBookInputParameterResult(
            ImmutableArray<Outputs.GetSchedulerDefinitionRunBookInputParameterArgumentResult> arguments,

            string stepName)
        {
            Arguments = arguments;
            StepName = stepName;
        }
    }
}
