// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.oci.AiAnomalyDetection.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.oci.AiAnomalyDetection.outputs.GetDetectAnomalyJobInputDetailData;
import com.pulumi.oci.AiAnomalyDetection.outputs.GetDetectAnomalyJobInputDetailObjectLocation;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetDetectAnomalyJobInputDetail {
    private @Nullable String content;
    private @Nullable String contentType;
    private @Nullable List<GetDetectAnomalyJobInputDetailData> datas;
    /**
     * @return The type of input location Allowed values are:
     * 
     */
    private @Nullable String inputType;
    /**
     * @return Inline input details.
     * 
     */
    private @Nullable String message;
    /**
     * @return List of ObjectLocations.
     * 
     */
    private @Nullable List<GetDetectAnomalyJobInputDetailObjectLocation> objectLocations;
    private @Nullable List<String> signalNames;

    private GetDetectAnomalyJobInputDetail() {}
    public Optional<String> content() {
        return Optional.ofNullable(this.content);
    }
    public Optional<String> contentType() {
        return Optional.ofNullable(this.contentType);
    }
    public List<GetDetectAnomalyJobInputDetailData> datas() {
        return this.datas == null ? List.of() : this.datas;
    }
    /**
     * @return The type of input location Allowed values are:
     * 
     */
    public Optional<String> inputType() {
        return Optional.ofNullable(this.inputType);
    }
    /**
     * @return Inline input details.
     * 
     */
    public Optional<String> message() {
        return Optional.ofNullable(this.message);
    }
    /**
     * @return List of ObjectLocations.
     * 
     */
    public List<GetDetectAnomalyJobInputDetailObjectLocation> objectLocations() {
        return this.objectLocations == null ? List.of() : this.objectLocations;
    }
    public List<String> signalNames() {
        return this.signalNames == null ? List.of() : this.signalNames;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetDetectAnomalyJobInputDetail defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String content;
        private @Nullable String contentType;
        private @Nullable List<GetDetectAnomalyJobInputDetailData> datas;
        private @Nullable String inputType;
        private @Nullable String message;
        private @Nullable List<GetDetectAnomalyJobInputDetailObjectLocation> objectLocations;
        private @Nullable List<String> signalNames;
        public Builder() {}
        public Builder(GetDetectAnomalyJobInputDetail defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.content = defaults.content;
    	      this.contentType = defaults.contentType;
    	      this.datas = defaults.datas;
    	      this.inputType = defaults.inputType;
    	      this.message = defaults.message;
    	      this.objectLocations = defaults.objectLocations;
    	      this.signalNames = defaults.signalNames;
        }

        @CustomType.Setter
        public Builder content(@Nullable String content) {
            this.content = content;
            return this;
        }
        @CustomType.Setter
        public Builder contentType(@Nullable String contentType) {
            this.contentType = contentType;
            return this;
        }
        @CustomType.Setter
        public Builder datas(@Nullable List<GetDetectAnomalyJobInputDetailData> datas) {
            this.datas = datas;
            return this;
        }
        public Builder datas(GetDetectAnomalyJobInputDetailData... datas) {
            return datas(List.of(datas));
        }
        @CustomType.Setter
        public Builder inputType(@Nullable String inputType) {
            this.inputType = inputType;
            return this;
        }
        @CustomType.Setter
        public Builder message(@Nullable String message) {
            this.message = message;
            return this;
        }
        @CustomType.Setter
        public Builder objectLocations(@Nullable List<GetDetectAnomalyJobInputDetailObjectLocation> objectLocations) {
            this.objectLocations = objectLocations;
            return this;
        }
        public Builder objectLocations(GetDetectAnomalyJobInputDetailObjectLocation... objectLocations) {
            return objectLocations(List.of(objectLocations));
        }
        @CustomType.Setter
        public Builder signalNames(@Nullable List<String> signalNames) {
            this.signalNames = signalNames;
            return this;
        }
        public Builder signalNames(String... signalNames) {
            return signalNames(List.of(signalNames));
        }
        public GetDetectAnomalyJobInputDetail build() {
            final var o = new GetDetectAnomalyJobInputDetail();
            o.content = content;
            o.contentType = contentType;
            o.datas = datas;
            o.inputType = inputType;
            o.message = message;
            o.objectLocations = objectLocations;
            o.signalNames = signalNames;
            return o;
        }
    }
}
