// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.oci.ApmTraces.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.oci.ApmTraces.outputs.GetTraceSpanLogSpanLog;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetTraceSpanLog {
    /**
     * @return List of logs associated with the span at the given timestamp.
     * 
     */
    private List<GetTraceSpanLogSpanLog> spanLogs;
    /**
     * @return Timestamp at which the log is created.
     * 
     */
    private String timeCreated;

    private GetTraceSpanLog() {}
    /**
     * @return List of logs associated with the span at the given timestamp.
     * 
     */
    public List<GetTraceSpanLogSpanLog> spanLogs() {
        return this.spanLogs;
    }
    /**
     * @return Timestamp at which the log is created.
     * 
     */
    public String timeCreated() {
        return this.timeCreated;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetTraceSpanLog defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<GetTraceSpanLogSpanLog> spanLogs;
        private String timeCreated;
        public Builder() {}
        public Builder(GetTraceSpanLog defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.spanLogs = defaults.spanLogs;
    	      this.timeCreated = defaults.timeCreated;
        }

        @CustomType.Setter
        public Builder spanLogs(List<GetTraceSpanLogSpanLog> spanLogs) {
            this.spanLogs = Objects.requireNonNull(spanLogs);
            return this;
        }
        public Builder spanLogs(GetTraceSpanLogSpanLog... spanLogs) {
            return spanLogs(List.of(spanLogs));
        }
        @CustomType.Setter
        public Builder timeCreated(String timeCreated) {
            this.timeCreated = Objects.requireNonNull(timeCreated);
            return this;
        }
        public GetTraceSpanLog build() {
            final var o = new GetTraceSpanLog();
            o.spanLogs = spanLogs;
            o.timeCreated = timeCreated;
            return o;
        }
    }
}
