// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.oci.Identity.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetDomainsCloudGatesCloudGateUpstreamServer {
    /**
     * @return Display name of upstream server
     * 
     */
    private String displayName;
    /**
     * @return Upstream Server Group instance for the upstream server. This is one of the upstreamServerGroup IDs(upstream blocks) from the associated Cloud Gate list
     * 
     */
    private String groupId;
    /**
     * @return Any incoming request to cloud gate is finally sent to this host, if selected during load balancing
     * 
     */
    private String hostName;
    /**
     * @return Any additional settings for this upstream server in nginx configuration form
     * 
     */
    private String nginxSettings;
    /**
     * @return Port for the Upstream Server
     * 
     */
    private Integer port;
    /**
     * @return URI of the upstream server
     * 
     */
    private String ref;
    /**
     * @return ID of the upstream server
     * 
     */
    private String value;

    private GetDomainsCloudGatesCloudGateUpstreamServer() {}
    /**
     * @return Display name of upstream server
     * 
     */
    public String displayName() {
        return this.displayName;
    }
    /**
     * @return Upstream Server Group instance for the upstream server. This is one of the upstreamServerGroup IDs(upstream blocks) from the associated Cloud Gate list
     * 
     */
    public String groupId() {
        return this.groupId;
    }
    /**
     * @return Any incoming request to cloud gate is finally sent to this host, if selected during load balancing
     * 
     */
    public String hostName() {
        return this.hostName;
    }
    /**
     * @return Any additional settings for this upstream server in nginx configuration form
     * 
     */
    public String nginxSettings() {
        return this.nginxSettings;
    }
    /**
     * @return Port for the Upstream Server
     * 
     */
    public Integer port() {
        return this.port;
    }
    /**
     * @return URI of the upstream server
     * 
     */
    public String ref() {
        return this.ref;
    }
    /**
     * @return ID of the upstream server
     * 
     */
    public String value() {
        return this.value;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetDomainsCloudGatesCloudGateUpstreamServer defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String displayName;
        private String groupId;
        private String hostName;
        private String nginxSettings;
        private Integer port;
        private String ref;
        private String value;
        public Builder() {}
        public Builder(GetDomainsCloudGatesCloudGateUpstreamServer defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.displayName = defaults.displayName;
    	      this.groupId = defaults.groupId;
    	      this.hostName = defaults.hostName;
    	      this.nginxSettings = defaults.nginxSettings;
    	      this.port = defaults.port;
    	      this.ref = defaults.ref;
    	      this.value = defaults.value;
        }

        @CustomType.Setter
        public Builder displayName(String displayName) {
            if (displayName == null) {
              throw new MissingRequiredPropertyException("GetDomainsCloudGatesCloudGateUpstreamServer", "displayName");
            }
            this.displayName = displayName;
            return this;
        }
        @CustomType.Setter
        public Builder groupId(String groupId) {
            if (groupId == null) {
              throw new MissingRequiredPropertyException("GetDomainsCloudGatesCloudGateUpstreamServer", "groupId");
            }
            this.groupId = groupId;
            return this;
        }
        @CustomType.Setter
        public Builder hostName(String hostName) {
            if (hostName == null) {
              throw new MissingRequiredPropertyException("GetDomainsCloudGatesCloudGateUpstreamServer", "hostName");
            }
            this.hostName = hostName;
            return this;
        }
        @CustomType.Setter
        public Builder nginxSettings(String nginxSettings) {
            if (nginxSettings == null) {
              throw new MissingRequiredPropertyException("GetDomainsCloudGatesCloudGateUpstreamServer", "nginxSettings");
            }
            this.nginxSettings = nginxSettings;
            return this;
        }
        @CustomType.Setter
        public Builder port(Integer port) {
            if (port == null) {
              throw new MissingRequiredPropertyException("GetDomainsCloudGatesCloudGateUpstreamServer", "port");
            }
            this.port = port;
            return this;
        }
        @CustomType.Setter
        public Builder ref(String ref) {
            if (ref == null) {
              throw new MissingRequiredPropertyException("GetDomainsCloudGatesCloudGateUpstreamServer", "ref");
            }
            this.ref = ref;
            return this;
        }
        @CustomType.Setter
        public Builder value(String value) {
            if (value == null) {
              throw new MissingRequiredPropertyException("GetDomainsCloudGatesCloudGateUpstreamServer", "value");
            }
            this.value = value;
            return this;
        }
        public GetDomainsCloudGatesCloudGateUpstreamServer build() {
            final var _resultValue = new GetDomainsCloudGatesCloudGateUpstreamServer();
            _resultValue.displayName = displayName;
            _resultValue.groupId = groupId;
            _resultValue.hostName = hostName;
            _resultValue.nginxSettings = nginxSettings;
            _resultValue.port = port;
            _resultValue.ref = ref;
            _resultValue.value = value;
            return _resultValue;
        }
    }
}
