// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.oci.Identity.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetTagValidator {
    /**
     * @return Specifies the type of validation: a static value (no validation) or a list.
     * 
     */
    private String validatorType;
    /**
     * @return The list of allowed values for a definedTag value.
     * 
     */
    private List<String> values;

    private GetTagValidator() {}
    /**
     * @return Specifies the type of validation: a static value (no validation) or a list.
     * 
     */
    public String validatorType() {
        return this.validatorType;
    }
    /**
     * @return The list of allowed values for a definedTag value.
     * 
     */
    public List<String> values() {
        return this.values;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetTagValidator defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String validatorType;
        private List<String> values;
        public Builder() {}
        public Builder(GetTagValidator defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.validatorType = defaults.validatorType;
    	      this.values = defaults.values;
        }

        @CustomType.Setter
        public Builder validatorType(String validatorType) {
            if (validatorType == null) {
              throw new MissingRequiredPropertyException("GetTagValidator", "validatorType");
            }
            this.validatorType = validatorType;
            return this;
        }
        @CustomType.Setter
        public Builder values(List<String> values) {
            if (values == null) {
              throw new MissingRequiredPropertyException("GetTagValidator", "values");
            }
            this.values = values;
            return this;
        }
        public Builder values(String... values) {
            return values(List.of(values));
        }
        public GetTagValidator build() {
            final var _resultValue = new GetTagValidator();
            _resultValue.validatorType = validatorType;
            _resultValue.values = values;
            return _resultValue;
        }
    }
}
