// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.oci.OsManagementHub;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.oci.OsManagementHub.inputs.ManagedInstanceGroupInstallPackagesManagementWorkRequestDetailsArgs;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ManagedInstanceGroupInstallPackagesManagementArgs extends com.pulumi.resources.ResourceArgs {

    public static final ManagedInstanceGroupInstallPackagesManagementArgs Empty = new ManagedInstanceGroupInstallPackagesManagementArgs();

    /**
     * Indicates whether this is the latest package version.
     * 
     */
    @Import(name="isLatest")
    private @Nullable Output<Boolean> isLatest;

    /**
     * @return Indicates whether this is the latest package version.
     * 
     */
    public Optional<Output<Boolean>> isLatest() {
        return Optional.ofNullable(this.isLatest);
    }

    /**
     * The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the managed instance group.
     * 
     */
    @Import(name="managedInstanceGroupId", required=true)
    private Output<String> managedInstanceGroupId;

    /**
     * @return The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the managed instance group.
     * 
     */
    public Output<String> managedInstanceGroupId() {
        return this.managedInstanceGroupId;
    }

    /**
     * The list of package names.
     * 
     */
    @Import(name="packageNames", required=true)
    private Output<List<String>> packageNames;

    /**
     * @return The list of package names.
     * 
     */
    public Output<List<String>> packageNames() {
        return this.packageNames;
    }

    /**
     * Provides the name and description of the job.
     * 
     */
    @Import(name="workRequestDetails")
    private @Nullable Output<ManagedInstanceGroupInstallPackagesManagementWorkRequestDetailsArgs> workRequestDetails;

    /**
     * @return Provides the name and description of the job.
     * 
     */
    public Optional<Output<ManagedInstanceGroupInstallPackagesManagementWorkRequestDetailsArgs>> workRequestDetails() {
        return Optional.ofNullable(this.workRequestDetails);
    }

    private ManagedInstanceGroupInstallPackagesManagementArgs() {}

    private ManagedInstanceGroupInstallPackagesManagementArgs(ManagedInstanceGroupInstallPackagesManagementArgs $) {
        this.isLatest = $.isLatest;
        this.managedInstanceGroupId = $.managedInstanceGroupId;
        this.packageNames = $.packageNames;
        this.workRequestDetails = $.workRequestDetails;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ManagedInstanceGroupInstallPackagesManagementArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ManagedInstanceGroupInstallPackagesManagementArgs $;

        public Builder() {
            $ = new ManagedInstanceGroupInstallPackagesManagementArgs();
        }

        public Builder(ManagedInstanceGroupInstallPackagesManagementArgs defaults) {
            $ = new ManagedInstanceGroupInstallPackagesManagementArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param isLatest Indicates whether this is the latest package version.
         * 
         * @return builder
         * 
         */
        public Builder isLatest(@Nullable Output<Boolean> isLatest) {
            $.isLatest = isLatest;
            return this;
        }

        /**
         * @param isLatest Indicates whether this is the latest package version.
         * 
         * @return builder
         * 
         */
        public Builder isLatest(Boolean isLatest) {
            return isLatest(Output.of(isLatest));
        }

        /**
         * @param managedInstanceGroupId The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the managed instance group.
         * 
         * @return builder
         * 
         */
        public Builder managedInstanceGroupId(Output<String> managedInstanceGroupId) {
            $.managedInstanceGroupId = managedInstanceGroupId;
            return this;
        }

        /**
         * @param managedInstanceGroupId The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the managed instance group.
         * 
         * @return builder
         * 
         */
        public Builder managedInstanceGroupId(String managedInstanceGroupId) {
            return managedInstanceGroupId(Output.of(managedInstanceGroupId));
        }

        /**
         * @param packageNames The list of package names.
         * 
         * @return builder
         * 
         */
        public Builder packageNames(Output<List<String>> packageNames) {
            $.packageNames = packageNames;
            return this;
        }

        /**
         * @param packageNames The list of package names.
         * 
         * @return builder
         * 
         */
        public Builder packageNames(List<String> packageNames) {
            return packageNames(Output.of(packageNames));
        }

        /**
         * @param packageNames The list of package names.
         * 
         * @return builder
         * 
         */
        public Builder packageNames(String... packageNames) {
            return packageNames(List.of(packageNames));
        }

        /**
         * @param workRequestDetails Provides the name and description of the job.
         * 
         * @return builder
         * 
         */
        public Builder workRequestDetails(@Nullable Output<ManagedInstanceGroupInstallPackagesManagementWorkRequestDetailsArgs> workRequestDetails) {
            $.workRequestDetails = workRequestDetails;
            return this;
        }

        /**
         * @param workRequestDetails Provides the name and description of the job.
         * 
         * @return builder
         * 
         */
        public Builder workRequestDetails(ManagedInstanceGroupInstallPackagesManagementWorkRequestDetailsArgs workRequestDetails) {
            return workRequestDetails(Output.of(workRequestDetails));
        }

        public ManagedInstanceGroupInstallPackagesManagementArgs build() {
            if ($.managedInstanceGroupId == null) {
                throw new MissingRequiredPropertyException("ManagedInstanceGroupInstallPackagesManagementArgs", "managedInstanceGroupId");
            }
            if ($.packageNames == null) {
                throw new MissingRequiredPropertyException("ManagedInstanceGroupInstallPackagesManagementArgs", "packageNames");
            }
            return $;
        }
    }

}
