// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.oci.DevOps.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DeploymentDeployStageOverrideArgumentsItemArgs extends com.pulumi.resources.ResourceArgs {

    public static final DeploymentDeployStageOverrideArgumentsItemArgs Empty = new DeploymentDeployStageOverrideArgumentsItemArgs();

    /**
     * The OCID of the stage.
     * 
     */
    @Import(name="deployStageId")
    private @Nullable Output<String> deployStageId;

    /**
     * @return The OCID of the stage.
     * 
     */
    public Optional<Output<String>> deployStageId() {
        return Optional.ofNullable(this.deployStageId);
    }

    /**
     * Name of the parameter (case-sensitive).
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Name of the parameter (case-sensitive).
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * Value of the parameter.
     * 
     */
    @Import(name="value")
    private @Nullable Output<String> value;

    /**
     * @return Value of the parameter.
     * 
     */
    public Optional<Output<String>> value() {
        return Optional.ofNullable(this.value);
    }

    private DeploymentDeployStageOverrideArgumentsItemArgs() {}

    private DeploymentDeployStageOverrideArgumentsItemArgs(DeploymentDeployStageOverrideArgumentsItemArgs $) {
        this.deployStageId = $.deployStageId;
        this.name = $.name;
        this.value = $.value;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DeploymentDeployStageOverrideArgumentsItemArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DeploymentDeployStageOverrideArgumentsItemArgs $;

        public Builder() {
            $ = new DeploymentDeployStageOverrideArgumentsItemArgs();
        }

        public Builder(DeploymentDeployStageOverrideArgumentsItemArgs defaults) {
            $ = new DeploymentDeployStageOverrideArgumentsItemArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param deployStageId The OCID of the stage.
         * 
         * @return builder
         * 
         */
        public Builder deployStageId(@Nullable Output<String> deployStageId) {
            $.deployStageId = deployStageId;
            return this;
        }

        /**
         * @param deployStageId The OCID of the stage.
         * 
         * @return builder
         * 
         */
        public Builder deployStageId(String deployStageId) {
            return deployStageId(Output.of(deployStageId));
        }

        /**
         * @param name Name of the parameter (case-sensitive).
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Name of the parameter (case-sensitive).
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param value Value of the parameter.
         * 
         * @return builder
         * 
         */
        public Builder value(@Nullable Output<String> value) {
            $.value = value;
            return this;
        }

        /**
         * @param value Value of the parameter.
         * 
         * @return builder
         * 
         */
        public Builder value(String value) {
            return value(Output.of(value));
        }

        public DeploymentDeployStageOverrideArgumentsItemArgs build() {
            return $;
        }
    }

}
