# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs
from ._inputs import *

__all__ = ['ManagedInstanceRemoveSnapsManagementArgs', 'ManagedInstanceRemoveSnapsManagement']

@pulumi.input_type
class ManagedInstanceRemoveSnapsManagementArgs:
    def __init__(__self__, *,
                 managed_instance_id: pulumi.Input[_builtins.str],
                 snap_details: pulumi.Input[Sequence[pulumi.Input['ManagedInstanceRemoveSnapsManagementSnapDetailArgs']]],
                 work_request_details: Optional[pulumi.Input['ManagedInstanceRemoveSnapsManagementWorkRequestDetailsArgs']] = None):
        """
        The set of arguments for constructing a ManagedInstanceRemoveSnapsManagement resource.

        :param pulumi.Input[_builtins.str] managed_instance_id: The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the managed instance.
        :param pulumi.Input[Sequence[pulumi.Input['ManagedInstanceRemoveSnapsManagementSnapDetailArgs']]] snap_details: The array of snaps to remove.
        :param pulumi.Input['ManagedInstanceRemoveSnapsManagementWorkRequestDetailsArgs'] work_request_details: Provides the name and description of the job.
        """
        pulumi.set(__self__, "managed_instance_id", managed_instance_id)
        pulumi.set(__self__, "snap_details", snap_details)
        if work_request_details is not None:
            pulumi.set(__self__, "work_request_details", work_request_details)

    @_builtins.property
    @pulumi.getter(name="managedInstanceId")
    def managed_instance_id(self) -> pulumi.Input[_builtins.str]:
        """
        The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the managed instance.
        """
        return pulumi.get(self, "managed_instance_id")

    @managed_instance_id.setter
    def managed_instance_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "managed_instance_id", value)

    @_builtins.property
    @pulumi.getter(name="snapDetails")
    def snap_details(self) -> pulumi.Input[Sequence[pulumi.Input['ManagedInstanceRemoveSnapsManagementSnapDetailArgs']]]:
        """
        The array of snaps to remove.
        """
        return pulumi.get(self, "snap_details")

    @snap_details.setter
    def snap_details(self, value: pulumi.Input[Sequence[pulumi.Input['ManagedInstanceRemoveSnapsManagementSnapDetailArgs']]]):
        pulumi.set(self, "snap_details", value)

    @_builtins.property
    @pulumi.getter(name="workRequestDetails")
    def work_request_details(self) -> Optional[pulumi.Input['ManagedInstanceRemoveSnapsManagementWorkRequestDetailsArgs']]:
        """
        Provides the name and description of the job.
        """
        return pulumi.get(self, "work_request_details")

    @work_request_details.setter
    def work_request_details(self, value: Optional[pulumi.Input['ManagedInstanceRemoveSnapsManagementWorkRequestDetailsArgs']]):
        pulumi.set(self, "work_request_details", value)


@pulumi.input_type
class _ManagedInstanceRemoveSnapsManagementState:
    def __init__(__self__, *,
                 managed_instance_id: Optional[pulumi.Input[_builtins.str]] = None,
                 snap_details: Optional[pulumi.Input[Sequence[pulumi.Input['ManagedInstanceRemoveSnapsManagementSnapDetailArgs']]]] = None,
                 work_request_details: Optional[pulumi.Input['ManagedInstanceRemoveSnapsManagementWorkRequestDetailsArgs']] = None):
        """
        Input properties used for looking up and filtering ManagedInstanceRemoveSnapsManagement resources.

        :param pulumi.Input[_builtins.str] managed_instance_id: The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the managed instance.
        :param pulumi.Input[Sequence[pulumi.Input['ManagedInstanceRemoveSnapsManagementSnapDetailArgs']]] snap_details: The array of snaps to remove.
        :param pulumi.Input['ManagedInstanceRemoveSnapsManagementWorkRequestDetailsArgs'] work_request_details: Provides the name and description of the job.
        """
        if managed_instance_id is not None:
            pulumi.set(__self__, "managed_instance_id", managed_instance_id)
        if snap_details is not None:
            pulumi.set(__self__, "snap_details", snap_details)
        if work_request_details is not None:
            pulumi.set(__self__, "work_request_details", work_request_details)

    @_builtins.property
    @pulumi.getter(name="managedInstanceId")
    def managed_instance_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the managed instance.
        """
        return pulumi.get(self, "managed_instance_id")

    @managed_instance_id.setter
    def managed_instance_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "managed_instance_id", value)

    @_builtins.property
    @pulumi.getter(name="snapDetails")
    def snap_details(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['ManagedInstanceRemoveSnapsManagementSnapDetailArgs']]]]:
        """
        The array of snaps to remove.
        """
        return pulumi.get(self, "snap_details")

    @snap_details.setter
    def snap_details(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['ManagedInstanceRemoveSnapsManagementSnapDetailArgs']]]]):
        pulumi.set(self, "snap_details", value)

    @_builtins.property
    @pulumi.getter(name="workRequestDetails")
    def work_request_details(self) -> Optional[pulumi.Input['ManagedInstanceRemoveSnapsManagementWorkRequestDetailsArgs']]:
        """
        Provides the name and description of the job.
        """
        return pulumi.get(self, "work_request_details")

    @work_request_details.setter
    def work_request_details(self, value: Optional[pulumi.Input['ManagedInstanceRemoveSnapsManagementWorkRequestDetailsArgs']]):
        pulumi.set(self, "work_request_details", value)


@pulumi.type_token("oci:OsManagementHub/managedInstanceRemoveSnapsManagement:ManagedInstanceRemoveSnapsManagement")
class ManagedInstanceRemoveSnapsManagement(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 managed_instance_id: Optional[pulumi.Input[_builtins.str]] = None,
                 snap_details: Optional[pulumi.Input[Sequence[pulumi.Input[Union['ManagedInstanceRemoveSnapsManagementSnapDetailArgs', 'ManagedInstanceRemoveSnapsManagementSnapDetailArgsDict']]]]] = None,
                 work_request_details: Optional[pulumi.Input[Union['ManagedInstanceRemoveSnapsManagementWorkRequestDetailsArgs', 'ManagedInstanceRemoveSnapsManagementWorkRequestDetailsArgsDict']]] = None,
                 __props__=None):
        """
        This resource provides the Managed Instance Remove Snaps Management resource in Oracle Cloud Infrastructure Os Management Hub service.
        Api doc link for the resource: https://docs.oracle.com/iaas/api/#/en/osmh/latest/ManagedInstance/RemoveSnaps

        Example terraform configs related to the resource : https://github.com/oracle/terraform-provider-oci/tree/master/examples/os_management_hub

        Removes specified snaps from a managed instance.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_oci as oci

        test_managed_instance_remove_snaps_management = oci.osmanagementhub.ManagedInstanceRemoveSnapsManagement("test_managed_instance_remove_snaps_management",
            managed_instance_id=test_managed_instance["id"],
            snap_details=[{
                "name": managed_instance_remove_snaps_management_snap_details_name,
                "revision": managed_instance_remove_snaps_management_snap_details_revision,
            }],
            work_request_details={
                "description": managed_instance_remove_snaps_management_work_request_details_description,
                "display_name": managed_instance_remove_snaps_management_work_request_details_display_name,
            })
        ```

        ## Import

        ManagedInstanceRemoveSnapsManagement can be imported using the `id`, e.g.

        ```sh
        $ pulumi import oci:OsManagementHub/managedInstanceRemoveSnapsManagement:ManagedInstanceRemoveSnapsManagement test_managed_instance_remove_snaps_management "id"
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] managed_instance_id: The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the managed instance.
        :param pulumi.Input[Sequence[pulumi.Input[Union['ManagedInstanceRemoveSnapsManagementSnapDetailArgs', 'ManagedInstanceRemoveSnapsManagementSnapDetailArgsDict']]]] snap_details: The array of snaps to remove.
        :param pulumi.Input[Union['ManagedInstanceRemoveSnapsManagementWorkRequestDetailsArgs', 'ManagedInstanceRemoveSnapsManagementWorkRequestDetailsArgsDict']] work_request_details: Provides the name and description of the job.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ManagedInstanceRemoveSnapsManagementArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        This resource provides the Managed Instance Remove Snaps Management resource in Oracle Cloud Infrastructure Os Management Hub service.
        Api doc link for the resource: https://docs.oracle.com/iaas/api/#/en/osmh/latest/ManagedInstance/RemoveSnaps

        Example terraform configs related to the resource : https://github.com/oracle/terraform-provider-oci/tree/master/examples/os_management_hub

        Removes specified snaps from a managed instance.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_oci as oci

        test_managed_instance_remove_snaps_management = oci.osmanagementhub.ManagedInstanceRemoveSnapsManagement("test_managed_instance_remove_snaps_management",
            managed_instance_id=test_managed_instance["id"],
            snap_details=[{
                "name": managed_instance_remove_snaps_management_snap_details_name,
                "revision": managed_instance_remove_snaps_management_snap_details_revision,
            }],
            work_request_details={
                "description": managed_instance_remove_snaps_management_work_request_details_description,
                "display_name": managed_instance_remove_snaps_management_work_request_details_display_name,
            })
        ```

        ## Import

        ManagedInstanceRemoveSnapsManagement can be imported using the `id`, e.g.

        ```sh
        $ pulumi import oci:OsManagementHub/managedInstanceRemoveSnapsManagement:ManagedInstanceRemoveSnapsManagement test_managed_instance_remove_snaps_management "id"
        ```


        :param str resource_name: The name of the resource.
        :param ManagedInstanceRemoveSnapsManagementArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ManagedInstanceRemoveSnapsManagementArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 managed_instance_id: Optional[pulumi.Input[_builtins.str]] = None,
                 snap_details: Optional[pulumi.Input[Sequence[pulumi.Input[Union['ManagedInstanceRemoveSnapsManagementSnapDetailArgs', 'ManagedInstanceRemoveSnapsManagementSnapDetailArgsDict']]]]] = None,
                 work_request_details: Optional[pulumi.Input[Union['ManagedInstanceRemoveSnapsManagementWorkRequestDetailsArgs', 'ManagedInstanceRemoveSnapsManagementWorkRequestDetailsArgsDict']]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ManagedInstanceRemoveSnapsManagementArgs.__new__(ManagedInstanceRemoveSnapsManagementArgs)

            if managed_instance_id is None and not opts.urn:
                raise TypeError("Missing required property 'managed_instance_id'")
            __props__.__dict__["managed_instance_id"] = managed_instance_id
            if snap_details is None and not opts.urn:
                raise TypeError("Missing required property 'snap_details'")
            __props__.__dict__["snap_details"] = snap_details
            __props__.__dict__["work_request_details"] = work_request_details
        super(ManagedInstanceRemoveSnapsManagement, __self__).__init__(
            'oci:OsManagementHub/managedInstanceRemoveSnapsManagement:ManagedInstanceRemoveSnapsManagement',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            managed_instance_id: Optional[pulumi.Input[_builtins.str]] = None,
            snap_details: Optional[pulumi.Input[Sequence[pulumi.Input[Union['ManagedInstanceRemoveSnapsManagementSnapDetailArgs', 'ManagedInstanceRemoveSnapsManagementSnapDetailArgsDict']]]]] = None,
            work_request_details: Optional[pulumi.Input[Union['ManagedInstanceRemoveSnapsManagementWorkRequestDetailsArgs', 'ManagedInstanceRemoveSnapsManagementWorkRequestDetailsArgsDict']]] = None) -> 'ManagedInstanceRemoveSnapsManagement':
        """
        Get an existing ManagedInstanceRemoveSnapsManagement resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] managed_instance_id: The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the managed instance.
        :param pulumi.Input[Sequence[pulumi.Input[Union['ManagedInstanceRemoveSnapsManagementSnapDetailArgs', 'ManagedInstanceRemoveSnapsManagementSnapDetailArgsDict']]]] snap_details: The array of snaps to remove.
        :param pulumi.Input[Union['ManagedInstanceRemoveSnapsManagementWorkRequestDetailsArgs', 'ManagedInstanceRemoveSnapsManagementWorkRequestDetailsArgsDict']] work_request_details: Provides the name and description of the job.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ManagedInstanceRemoveSnapsManagementState.__new__(_ManagedInstanceRemoveSnapsManagementState)

        __props__.__dict__["managed_instance_id"] = managed_instance_id
        __props__.__dict__["snap_details"] = snap_details
        __props__.__dict__["work_request_details"] = work_request_details
        return ManagedInstanceRemoveSnapsManagement(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="managedInstanceId")
    def managed_instance_id(self) -> pulumi.Output[_builtins.str]:
        """
        The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the managed instance.
        """
        return pulumi.get(self, "managed_instance_id")

    @_builtins.property
    @pulumi.getter(name="snapDetails")
    def snap_details(self) -> pulumi.Output[Sequence['outputs.ManagedInstanceRemoveSnapsManagementSnapDetail']]:
        """
        The array of snaps to remove.
        """
        return pulumi.get(self, "snap_details")

    @_builtins.property
    @pulumi.getter(name="workRequestDetails")
    def work_request_details(self) -> pulumi.Output['outputs.ManagedInstanceRemoveSnapsManagementWorkRequestDetails']:
        """
        Provides the name and description of the job.
        """
        return pulumi.get(self, "work_request_details")

