// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package database

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-oci/sdk/go/oci/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This data source provides the list of Autonomous Virtual Machines in Oracle Cloud Infrastructure Database service.
//
// Lists the Autonomous Virtual Machines in the specified Autonomous VM Cluster and Compartment.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-oci/sdk/go/oci/Database"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := Database.GetAutonomousVirtualMachines(ctx, &database.GetAutonomousVirtualMachinesArgs{
//				AutonomousVmClusterId: oci_database_autonomous_vm_cluster.Test_autonomous_vm_cluster.Id,
//				CompartmentId:         _var.Compartment_id,
//				State:                 pulumi.StringRef(_var.Autonomous_virtual_machine_state),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetAutonomousVirtualMachines(ctx *pulumi.Context, args *GetAutonomousVirtualMachinesArgs, opts ...pulumi.InvokeOption) (*GetAutonomousVirtualMachinesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetAutonomousVirtualMachinesResult
	err := ctx.Invoke("oci:Database/getAutonomousVirtualMachines:getAutonomousVirtualMachines", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getAutonomousVirtualMachines.
type GetAutonomousVirtualMachinesArgs struct {
	// The Autonomous Virtual machine [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm).
	AutonomousVmClusterId string `pulumi:"autonomousVmClusterId"`
	// The compartment [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm).
	CompartmentId string                               `pulumi:"compartmentId"`
	Filters       []GetAutonomousVirtualMachinesFilter `pulumi:"filters"`
	// A filter to return only resources that match the given lifecycle state exactly.
	State *string `pulumi:"state"`
}

// A collection of values returned by getAutonomousVirtualMachines.
type GetAutonomousVirtualMachinesResult struct {
	// The list of autonomous_virtual_machines.
	AutonomousVirtualMachines []GetAutonomousVirtualMachinesAutonomousVirtualMachine `pulumi:"autonomousVirtualMachines"`
	// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the Autonomous VM Cluster associated with the Autonomous Virtual Machine.
	AutonomousVmClusterId string `pulumi:"autonomousVmClusterId"`
	// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment.
	CompartmentId string                               `pulumi:"compartmentId"`
	Filters       []GetAutonomousVirtualMachinesFilter `pulumi:"filters"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The current state of the Autonomous Virtual Machine.
	State *string `pulumi:"state"`
}

func GetAutonomousVirtualMachinesOutput(ctx *pulumi.Context, args GetAutonomousVirtualMachinesOutputArgs, opts ...pulumi.InvokeOption) GetAutonomousVirtualMachinesResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetAutonomousVirtualMachinesResult, error) {
			args := v.(GetAutonomousVirtualMachinesArgs)
			r, err := GetAutonomousVirtualMachines(ctx, &args, opts...)
			var s GetAutonomousVirtualMachinesResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetAutonomousVirtualMachinesResultOutput)
}

// A collection of arguments for invoking getAutonomousVirtualMachines.
type GetAutonomousVirtualMachinesOutputArgs struct {
	// The Autonomous Virtual machine [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm).
	AutonomousVmClusterId pulumi.StringInput `pulumi:"autonomousVmClusterId"`
	// The compartment [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm).
	CompartmentId pulumi.StringInput                           `pulumi:"compartmentId"`
	Filters       GetAutonomousVirtualMachinesFilterArrayInput `pulumi:"filters"`
	// A filter to return only resources that match the given lifecycle state exactly.
	State pulumi.StringPtrInput `pulumi:"state"`
}

func (GetAutonomousVirtualMachinesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAutonomousVirtualMachinesArgs)(nil)).Elem()
}

// A collection of values returned by getAutonomousVirtualMachines.
type GetAutonomousVirtualMachinesResultOutput struct{ *pulumi.OutputState }

func (GetAutonomousVirtualMachinesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAutonomousVirtualMachinesResult)(nil)).Elem()
}

func (o GetAutonomousVirtualMachinesResultOutput) ToGetAutonomousVirtualMachinesResultOutput() GetAutonomousVirtualMachinesResultOutput {
	return o
}

func (o GetAutonomousVirtualMachinesResultOutput) ToGetAutonomousVirtualMachinesResultOutputWithContext(ctx context.Context) GetAutonomousVirtualMachinesResultOutput {
	return o
}

// The list of autonomous_virtual_machines.
func (o GetAutonomousVirtualMachinesResultOutput) AutonomousVirtualMachines() GetAutonomousVirtualMachinesAutonomousVirtualMachineArrayOutput {
	return o.ApplyT(func(v GetAutonomousVirtualMachinesResult) []GetAutonomousVirtualMachinesAutonomousVirtualMachine {
		return v.AutonomousVirtualMachines
	}).(GetAutonomousVirtualMachinesAutonomousVirtualMachineArrayOutput)
}

// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the Autonomous VM Cluster associated with the Autonomous Virtual Machine.
func (o GetAutonomousVirtualMachinesResultOutput) AutonomousVmClusterId() pulumi.StringOutput {
	return o.ApplyT(func(v GetAutonomousVirtualMachinesResult) string { return v.AutonomousVmClusterId }).(pulumi.StringOutput)
}

// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment.
func (o GetAutonomousVirtualMachinesResultOutput) CompartmentId() pulumi.StringOutput {
	return o.ApplyT(func(v GetAutonomousVirtualMachinesResult) string { return v.CompartmentId }).(pulumi.StringOutput)
}

func (o GetAutonomousVirtualMachinesResultOutput) Filters() GetAutonomousVirtualMachinesFilterArrayOutput {
	return o.ApplyT(func(v GetAutonomousVirtualMachinesResult) []GetAutonomousVirtualMachinesFilter { return v.Filters }).(GetAutonomousVirtualMachinesFilterArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetAutonomousVirtualMachinesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetAutonomousVirtualMachinesResult) string { return v.Id }).(pulumi.StringOutput)
}

// The current state of the Autonomous Virtual Machine.
func (o GetAutonomousVirtualMachinesResultOutput) State() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetAutonomousVirtualMachinesResult) *string { return v.State }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetAutonomousVirtualMachinesResultOutput{})
}
