// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Oci.DatabaseManagement.Outputs
{

    [OutputType]
    public sealed class GetCloudListenerServicesCloudListenerServiceCollectionItemResult
    {
        /// <summary>
        /// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the cloud listener.
        /// </summary>
        public readonly string ListenerId;
        /// <summary>
        /// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the Managed Database.
        /// </summary>
        public readonly string ManagedDatabaseId;
        /// <summary>
        /// The name of the service.
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private GetCloudListenerServicesCloudListenerServiceCollectionItemResult(
            string listenerId,

            string managedDatabaseId,

            string name)
        {
            ListenerId = listenerId;
            ManagedDatabaseId = managedDatabaseId;
            Name = name;
        }
    }
}
