// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Oci.DatabaseManagement.Outputs
{

    [OutputType]
    public sealed class GetExternalMySqlDatabasesExternalMySqlDatabaseCollectionItemResult
    {
        /// <summary>
        /// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment.
        /// </summary>
        public readonly string CompartmentId;
        /// <summary>
        /// Display Name of the External MySQL Database.
        /// </summary>
        public readonly string DbName;
        /// <summary>
        /// OCID of External MySQL Database.
        /// </summary>
        public readonly string ExternalDatabaseId;

        [OutputConstructor]
        private GetExternalMySqlDatabasesExternalMySqlDatabaseCollectionItemResult(
            string compartmentId,

            string dbName,

            string externalDatabaseId)
        {
            CompartmentId = compartmentId;
            DbName = dbName;
            ExternalDatabaseId = externalDatabaseId;
        }
    }
}
