// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.oci.BigDataService;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class BdsInstanceReplaceNodeActionArgs extends com.pulumi.resources.ResourceArgs {

    public static final BdsInstanceReplaceNodeActionArgs Empty = new BdsInstanceReplaceNodeActionArgs();

    /**
     * The OCID of the Big Data Service cluster.
     * 
     */
    @Import(name="bdsInstanceId", required=true)
    private Output<String> bdsInstanceId;

    /**
     * @return The OCID of the Big Data Service cluster.
     * 
     */
    public Output<String> bdsInstanceId() {
        return this.bdsInstanceId;
    }

    /**
     * Base64-encoded cluster admin password. Use this or `secretId`.
     * 
     */
    @Import(name="clusterAdminPassword")
    private @Nullable Output<String> clusterAdminPassword;

    /**
     * @return Base64-encoded cluster admin password. Use this or `secretId`.
     * 
     */
    public Optional<Output<String>> clusterAdminPassword() {
        return Optional.ofNullable(this.clusterAdminPassword);
    }

    /**
     * The OCID of the node backup to use for replacement.
     * 
     */
    @Import(name="nodeBackupId")
    private @Nullable Output<String> nodeBackupId;

    /**
     * @return The OCID of the node backup to use for replacement.
     * 
     */
    public Optional<Output<String>> nodeBackupId() {
        return Optional.ofNullable(this.nodeBackupId);
    }

    /**
     * Host name of the node to replace.
     * 
     */
    @Import(name="nodeHostName", required=true)
    private Output<String> nodeHostName;

    /**
     * @return Host name of the node to replace.
     * 
     */
    public Output<String> nodeHostName() {
        return this.nodeHostName;
    }

    /**
     * The OCID of the secret that stores the cluster admin password. Use this or `clusterAdminPassword`.
     * 
     */
    @Import(name="secretId")
    private @Nullable Output<String> secretId;

    /**
     * @return The OCID of the secret that stores the cluster admin password. Use this or `clusterAdminPassword`.
     * 
     */
    public Optional<Output<String>> secretId() {
        return Optional.ofNullable(this.secretId);
    }

    /**
     * The shape to use for the replacement node. If not specified, the existing node shape is used.
     * 
     * **IMPORTANT**
     * This is an action resource. Any change forces Terraform to create the action resource again and invoke the replace node workflow.
     * 
     */
    @Import(name="shape")
    private @Nullable Output<String> shape;

    /**
     * @return The shape to use for the replacement node. If not specified, the existing node shape is used.
     * 
     * **IMPORTANT**
     * This is an action resource. Any change forces Terraform to create the action resource again and invoke the replace node workflow.
     * 
     */
    public Optional<Output<String>> shape() {
        return Optional.ofNullable(this.shape);
    }

    private BdsInstanceReplaceNodeActionArgs() {}

    private BdsInstanceReplaceNodeActionArgs(BdsInstanceReplaceNodeActionArgs $) {
        this.bdsInstanceId = $.bdsInstanceId;
        this.clusterAdminPassword = $.clusterAdminPassword;
        this.nodeBackupId = $.nodeBackupId;
        this.nodeHostName = $.nodeHostName;
        this.secretId = $.secretId;
        this.shape = $.shape;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(BdsInstanceReplaceNodeActionArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private BdsInstanceReplaceNodeActionArgs $;

        public Builder() {
            $ = new BdsInstanceReplaceNodeActionArgs();
        }

        public Builder(BdsInstanceReplaceNodeActionArgs defaults) {
            $ = new BdsInstanceReplaceNodeActionArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param bdsInstanceId The OCID of the Big Data Service cluster.
         * 
         * @return builder
         * 
         */
        public Builder bdsInstanceId(Output<String> bdsInstanceId) {
            $.bdsInstanceId = bdsInstanceId;
            return this;
        }

        /**
         * @param bdsInstanceId The OCID of the Big Data Service cluster.
         * 
         * @return builder
         * 
         */
        public Builder bdsInstanceId(String bdsInstanceId) {
            return bdsInstanceId(Output.of(bdsInstanceId));
        }

        /**
         * @param clusterAdminPassword Base64-encoded cluster admin password. Use this or `secretId`.
         * 
         * @return builder
         * 
         */
        public Builder clusterAdminPassword(@Nullable Output<String> clusterAdminPassword) {
            $.clusterAdminPassword = clusterAdminPassword;
            return this;
        }

        /**
         * @param clusterAdminPassword Base64-encoded cluster admin password. Use this or `secretId`.
         * 
         * @return builder
         * 
         */
        public Builder clusterAdminPassword(String clusterAdminPassword) {
            return clusterAdminPassword(Output.of(clusterAdminPassword));
        }

        /**
         * @param nodeBackupId The OCID of the node backup to use for replacement.
         * 
         * @return builder
         * 
         */
        public Builder nodeBackupId(@Nullable Output<String> nodeBackupId) {
            $.nodeBackupId = nodeBackupId;
            return this;
        }

        /**
         * @param nodeBackupId The OCID of the node backup to use for replacement.
         * 
         * @return builder
         * 
         */
        public Builder nodeBackupId(String nodeBackupId) {
            return nodeBackupId(Output.of(nodeBackupId));
        }

        /**
         * @param nodeHostName Host name of the node to replace.
         * 
         * @return builder
         * 
         */
        public Builder nodeHostName(Output<String> nodeHostName) {
            $.nodeHostName = nodeHostName;
            return this;
        }

        /**
         * @param nodeHostName Host name of the node to replace.
         * 
         * @return builder
         * 
         */
        public Builder nodeHostName(String nodeHostName) {
            return nodeHostName(Output.of(nodeHostName));
        }

        /**
         * @param secretId The OCID of the secret that stores the cluster admin password. Use this or `clusterAdminPassword`.
         * 
         * @return builder
         * 
         */
        public Builder secretId(@Nullable Output<String> secretId) {
            $.secretId = secretId;
            return this;
        }

        /**
         * @param secretId The OCID of the secret that stores the cluster admin password. Use this or `clusterAdminPassword`.
         * 
         * @return builder
         * 
         */
        public Builder secretId(String secretId) {
            return secretId(Output.of(secretId));
        }

        /**
         * @param shape The shape to use for the replacement node. If not specified, the existing node shape is used.
         * 
         * **IMPORTANT**
         * This is an action resource. Any change forces Terraform to create the action resource again and invoke the replace node workflow.
         * 
         * @return builder
         * 
         */
        public Builder shape(@Nullable Output<String> shape) {
            $.shape = shape;
            return this;
        }

        /**
         * @param shape The shape to use for the replacement node. If not specified, the existing node shape is used.
         * 
         * **IMPORTANT**
         * This is an action resource. Any change forces Terraform to create the action resource again and invoke the replace node workflow.
         * 
         * @return builder
         * 
         */
        public Builder shape(String shape) {
            return shape(Output.of(shape));
        }

        public BdsInstanceReplaceNodeActionArgs build() {
            if ($.bdsInstanceId == null) {
                throw new MissingRequiredPropertyException("BdsInstanceReplaceNodeActionArgs", "bdsInstanceId");
            }
            if ($.nodeHostName == null) {
                throw new MissingRequiredPropertyException("BdsInstanceReplaceNodeActionArgs", "nodeHostName");
            }
            return $;
        }
    }

}
