// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export * from "./connectHarness";
export * from "./getConnectHarness";
export * from "./getConnectHarnesses";
export * from "./getStream";
export * from "./getStreamPool";
export * from "./getStreamPools";
export * from "./getStreams";
export * from "./stream";
export * from "./streamPool";

// Import resources to register:
import { ConnectHarness } from "./connectHarness";
import { Stream } from "./stream";
import { StreamPool } from "./streamPool";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "oci:Streaming/connectHarness:ConnectHarness":
                return new ConnectHarness(name, <any>undefined, { urn })
            case "oci:Streaming/stream:Stream":
                return new Stream(name, <any>undefined, { urn })
            case "oci:Streaming/streamPool:StreamPool":
                return new StreamPool(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("oci", "Streaming/connectHarness", _module)
pulumi.runtime.registerResourceModule("oci", "Streaming/stream", _module)
pulumi.runtime.registerResourceModule("oci", "Streaming/streamPool", _module)
