// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package databasemanagement

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-oci/sdk/v4/go/oci/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This resource provides the Cloud Db System resource in Oracle Cloud Infrastructure Database Management service.
// Api doc link for the resource: https://docs.oracle.com/iaas/api/#/en/database-management/latest/CloudDbSystem
//
// Example terraform configs related to the resource : https://github.com/oracle/terraform-provider-oci/tree/master/examples/databasemanagement
//
// Creates a cloud DB system and its related resources.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-oci/sdk/v4/go/oci/databasemanagement"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := databasemanagement.NewCloudDbSystem(ctx, "test_cloud_db_system", &databasemanagement.CloudDbSystemArgs{
//				CompartmentId:       pulumi.Any(compartmentId),
//				DbSystemDiscoveryId: pulumi.Any(testDbSystemDiscovery.Id),
//				DatabaseManagementConfig: &databasemanagement.CloudDbSystemDatabaseManagementConfigArgs{
//					IsEnabled: pulumi.Any(cloudDbSystemDatabaseManagementConfigIsEnabled),
//					Metadata:  pulumi.Any(cloudDbSystemDatabaseManagementConfigMetadata),
//				},
//				DefinedTags: pulumi.StringMap{
//					"Operations.CostCenter": pulumi.String("42"),
//				},
//				DisplayName: pulumi.Any(cloudDbSystemDisplayName),
//				FreeformTags: pulumi.StringMap{
//					"Department": pulumi.String("Finance"),
//				},
//				StackMonitoringConfig: &databasemanagement.CloudDbSystemStackMonitoringConfigArgs{
//					IsEnabled: pulumi.Any(cloudDbSystemStackMonitoringConfigIsEnabled),
//					Metadata:  pulumi.Any(cloudDbSystemStackMonitoringConfigMetadata),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// CloudDbSystems can be imported using the `id`, e.g.
//
// ```sh
// $ pulumi import oci:DatabaseManagement/cloudDbSystem:CloudDbSystem test_cloud_db_system "id"
// ```
type CloudDbSystem struct {
	pulumi.CustomResourceState

	// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment in which the cloud DB system resides.
	CompartmentId pulumi.StringOutput `pulumi:"compartmentId"`
	// The configuration details of Database Management for a cloud DB system.
	DatabaseManagementConfig CloudDbSystemDatabaseManagementConfigOutput `pulumi:"databaseManagementConfig"`
	// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the DB system discovery.
	DbSystemDiscoveryId pulumi.StringOutput `pulumi:"dbSystemDiscoveryId"`
	// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the parent cloud DB Infrastructure. For VM Dbsystems , it will be the DBSystem Id. For ExaCS and ExaCC,  it will be the cloudVmClusterId and vmClusterId respectively.
	DbaasParentInfrastructureId pulumi.StringOutput `pulumi:"dbaasParentInfrastructureId"`
	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see [Resource Tags](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm). Example: `{"Operations.CostCenter": "42"}`
	DefinedTags pulumi.StringMapOutput `pulumi:"definedTags"`
	// The deployment type of cloud dbsystem.
	DeploymentType pulumi.StringOutput `pulumi:"deploymentType"`
	// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the management agent used during the discovery of the DB system.
	DiscoveryAgentId pulumi.StringOutput `pulumi:"discoveryAgentId"`
	// (Updatable) The user-friendly name for the DB system. The name does not have to be unique.
	DisplayName pulumi.StringOutput `pulumi:"displayName"`
	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see [Resource Tags](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm). Example: `{"Department": "Finance"}`
	FreeformTags pulumi.StringMapOutput `pulumi:"freeformTags"`
	// The Oracle Grid home directory in case of cluster-based DB system and Oracle home directory in case of single instance-based DB system.
	HomeDirectory pulumi.StringOutput `pulumi:"homeDirectory"`
	// Indicates whether the DB system is a cluster DB system or not.
	IsCluster pulumi.BoolOutput `pulumi:"isCluster"`
	// Additional information about the current lifecycle state.
	LifecycleDetails pulumi.StringOutput `pulumi:"lifecycleDetails"`
	// The configuration details of Stack Monitoring for a cloud DB system.
	StackMonitoringConfig CloudDbSystemStackMonitoringConfigOutput `pulumi:"stackMonitoringConfig"`
	// The current lifecycle state of the cloud DB system resource.
	State pulumi.StringOutput `pulumi:"state"`
	// System tags for this resource. Each key is predefined and scoped to a namespace. For more information, see [Resource Tags](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm). System tags can be viewed by users, but can only be created by the system.  Example: `{"orcl-cloud.free-tier-retained": "true"}`
	SystemTags pulumi.StringMapOutput `pulumi:"systemTags"`
	// The date and time the cloud DB system was created.
	TimeCreated pulumi.StringOutput `pulumi:"timeCreated"`
	// The date and time the cloud DB system was last updated.
	TimeUpdated pulumi.StringOutput `pulumi:"timeUpdated"`
}

// NewCloudDbSystem registers a new resource with the given unique name, arguments, and options.
func NewCloudDbSystem(ctx *pulumi.Context,
	name string, args *CloudDbSystemArgs, opts ...pulumi.ResourceOption) (*CloudDbSystem, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.CompartmentId == nil {
		return nil, errors.New("invalid value for required argument 'CompartmentId'")
	}
	if args.DbSystemDiscoveryId == nil {
		return nil, errors.New("invalid value for required argument 'DbSystemDiscoveryId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource CloudDbSystem
	err := ctx.RegisterResource("oci:DatabaseManagement/cloudDbSystem:CloudDbSystem", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCloudDbSystem gets an existing CloudDbSystem resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCloudDbSystem(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CloudDbSystemState, opts ...pulumi.ResourceOption) (*CloudDbSystem, error) {
	var resource CloudDbSystem
	err := ctx.ReadResource("oci:DatabaseManagement/cloudDbSystem:CloudDbSystem", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering CloudDbSystem resources.
type cloudDbSystemState struct {
	// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment in which the cloud DB system resides.
	CompartmentId *string `pulumi:"compartmentId"`
	// The configuration details of Database Management for a cloud DB system.
	DatabaseManagementConfig *CloudDbSystemDatabaseManagementConfig `pulumi:"databaseManagementConfig"`
	// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the DB system discovery.
	DbSystemDiscoveryId *string `pulumi:"dbSystemDiscoveryId"`
	// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the parent cloud DB Infrastructure. For VM Dbsystems , it will be the DBSystem Id. For ExaCS and ExaCC,  it will be the cloudVmClusterId and vmClusterId respectively.
	DbaasParentInfrastructureId *string `pulumi:"dbaasParentInfrastructureId"`
	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see [Resource Tags](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm). Example: `{"Operations.CostCenter": "42"}`
	DefinedTags map[string]string `pulumi:"definedTags"`
	// The deployment type of cloud dbsystem.
	DeploymentType *string `pulumi:"deploymentType"`
	// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the management agent used during the discovery of the DB system.
	DiscoveryAgentId *string `pulumi:"discoveryAgentId"`
	// (Updatable) The user-friendly name for the DB system. The name does not have to be unique.
	DisplayName *string `pulumi:"displayName"`
	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see [Resource Tags](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm). Example: `{"Department": "Finance"}`
	FreeformTags map[string]string `pulumi:"freeformTags"`
	// The Oracle Grid home directory in case of cluster-based DB system and Oracle home directory in case of single instance-based DB system.
	HomeDirectory *string `pulumi:"homeDirectory"`
	// Indicates whether the DB system is a cluster DB system or not.
	IsCluster *bool `pulumi:"isCluster"`
	// Additional information about the current lifecycle state.
	LifecycleDetails *string `pulumi:"lifecycleDetails"`
	// The configuration details of Stack Monitoring for a cloud DB system.
	StackMonitoringConfig *CloudDbSystemStackMonitoringConfig `pulumi:"stackMonitoringConfig"`
	// The current lifecycle state of the cloud DB system resource.
	State *string `pulumi:"state"`
	// System tags for this resource. Each key is predefined and scoped to a namespace. For more information, see [Resource Tags](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm). System tags can be viewed by users, but can only be created by the system.  Example: `{"orcl-cloud.free-tier-retained": "true"}`
	SystemTags map[string]string `pulumi:"systemTags"`
	// The date and time the cloud DB system was created.
	TimeCreated *string `pulumi:"timeCreated"`
	// The date and time the cloud DB system was last updated.
	TimeUpdated *string `pulumi:"timeUpdated"`
}

type CloudDbSystemState struct {
	// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment in which the cloud DB system resides.
	CompartmentId pulumi.StringPtrInput
	// The configuration details of Database Management for a cloud DB system.
	DatabaseManagementConfig CloudDbSystemDatabaseManagementConfigPtrInput
	// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the DB system discovery.
	DbSystemDiscoveryId pulumi.StringPtrInput
	// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the parent cloud DB Infrastructure. For VM Dbsystems , it will be the DBSystem Id. For ExaCS and ExaCC,  it will be the cloudVmClusterId and vmClusterId respectively.
	DbaasParentInfrastructureId pulumi.StringPtrInput
	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see [Resource Tags](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm). Example: `{"Operations.CostCenter": "42"}`
	DefinedTags pulumi.StringMapInput
	// The deployment type of cloud dbsystem.
	DeploymentType pulumi.StringPtrInput
	// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the management agent used during the discovery of the DB system.
	DiscoveryAgentId pulumi.StringPtrInput
	// (Updatable) The user-friendly name for the DB system. The name does not have to be unique.
	DisplayName pulumi.StringPtrInput
	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see [Resource Tags](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm). Example: `{"Department": "Finance"}`
	FreeformTags pulumi.StringMapInput
	// The Oracle Grid home directory in case of cluster-based DB system and Oracle home directory in case of single instance-based DB system.
	HomeDirectory pulumi.StringPtrInput
	// Indicates whether the DB system is a cluster DB system or not.
	IsCluster pulumi.BoolPtrInput
	// Additional information about the current lifecycle state.
	LifecycleDetails pulumi.StringPtrInput
	// The configuration details of Stack Monitoring for a cloud DB system.
	StackMonitoringConfig CloudDbSystemStackMonitoringConfigPtrInput
	// The current lifecycle state of the cloud DB system resource.
	State pulumi.StringPtrInput
	// System tags for this resource. Each key is predefined and scoped to a namespace. For more information, see [Resource Tags](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm). System tags can be viewed by users, but can only be created by the system.  Example: `{"orcl-cloud.free-tier-retained": "true"}`
	SystemTags pulumi.StringMapInput
	// The date and time the cloud DB system was created.
	TimeCreated pulumi.StringPtrInput
	// The date and time the cloud DB system was last updated.
	TimeUpdated pulumi.StringPtrInput
}

func (CloudDbSystemState) ElementType() reflect.Type {
	return reflect.TypeOf((*cloudDbSystemState)(nil)).Elem()
}

type cloudDbSystemArgs struct {
	// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment in which the cloud DB system resides.
	CompartmentId string `pulumi:"compartmentId"`
	// The configuration details of Database Management for a cloud DB system.
	DatabaseManagementConfig *CloudDbSystemDatabaseManagementConfig `pulumi:"databaseManagementConfig"`
	// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the DB system discovery.
	DbSystemDiscoveryId string `pulumi:"dbSystemDiscoveryId"`
	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see [Resource Tags](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm). Example: `{"Operations.CostCenter": "42"}`
	DefinedTags map[string]string `pulumi:"definedTags"`
	// (Updatable) The user-friendly name for the DB system. The name does not have to be unique.
	DisplayName *string `pulumi:"displayName"`
	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see [Resource Tags](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm). Example: `{"Department": "Finance"}`
	FreeformTags map[string]string `pulumi:"freeformTags"`
	// The configuration details of Stack Monitoring for a cloud DB system.
	StackMonitoringConfig *CloudDbSystemStackMonitoringConfig `pulumi:"stackMonitoringConfig"`
}

// The set of arguments for constructing a CloudDbSystem resource.
type CloudDbSystemArgs struct {
	// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment in which the cloud DB system resides.
	CompartmentId pulumi.StringInput
	// The configuration details of Database Management for a cloud DB system.
	DatabaseManagementConfig CloudDbSystemDatabaseManagementConfigPtrInput
	// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the DB system discovery.
	DbSystemDiscoveryId pulumi.StringInput
	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see [Resource Tags](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm). Example: `{"Operations.CostCenter": "42"}`
	DefinedTags pulumi.StringMapInput
	// (Updatable) The user-friendly name for the DB system. The name does not have to be unique.
	DisplayName pulumi.StringPtrInput
	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see [Resource Tags](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm). Example: `{"Department": "Finance"}`
	FreeformTags pulumi.StringMapInput
	// The configuration details of Stack Monitoring for a cloud DB system.
	StackMonitoringConfig CloudDbSystemStackMonitoringConfigPtrInput
}

func (CloudDbSystemArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*cloudDbSystemArgs)(nil)).Elem()
}

type CloudDbSystemInput interface {
	pulumi.Input

	ToCloudDbSystemOutput() CloudDbSystemOutput
	ToCloudDbSystemOutputWithContext(ctx context.Context) CloudDbSystemOutput
}

func (*CloudDbSystem) ElementType() reflect.Type {
	return reflect.TypeOf((**CloudDbSystem)(nil)).Elem()
}

func (i *CloudDbSystem) ToCloudDbSystemOutput() CloudDbSystemOutput {
	return i.ToCloudDbSystemOutputWithContext(context.Background())
}

func (i *CloudDbSystem) ToCloudDbSystemOutputWithContext(ctx context.Context) CloudDbSystemOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CloudDbSystemOutput)
}

// CloudDbSystemArrayInput is an input type that accepts CloudDbSystemArray and CloudDbSystemArrayOutput values.
// You can construct a concrete instance of `CloudDbSystemArrayInput` via:
//
//	CloudDbSystemArray{ CloudDbSystemArgs{...} }
type CloudDbSystemArrayInput interface {
	pulumi.Input

	ToCloudDbSystemArrayOutput() CloudDbSystemArrayOutput
	ToCloudDbSystemArrayOutputWithContext(context.Context) CloudDbSystemArrayOutput
}

type CloudDbSystemArray []CloudDbSystemInput

func (CloudDbSystemArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CloudDbSystem)(nil)).Elem()
}

func (i CloudDbSystemArray) ToCloudDbSystemArrayOutput() CloudDbSystemArrayOutput {
	return i.ToCloudDbSystemArrayOutputWithContext(context.Background())
}

func (i CloudDbSystemArray) ToCloudDbSystemArrayOutputWithContext(ctx context.Context) CloudDbSystemArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CloudDbSystemArrayOutput)
}

// CloudDbSystemMapInput is an input type that accepts CloudDbSystemMap and CloudDbSystemMapOutput values.
// You can construct a concrete instance of `CloudDbSystemMapInput` via:
//
//	CloudDbSystemMap{ "key": CloudDbSystemArgs{...} }
type CloudDbSystemMapInput interface {
	pulumi.Input

	ToCloudDbSystemMapOutput() CloudDbSystemMapOutput
	ToCloudDbSystemMapOutputWithContext(context.Context) CloudDbSystemMapOutput
}

type CloudDbSystemMap map[string]CloudDbSystemInput

func (CloudDbSystemMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CloudDbSystem)(nil)).Elem()
}

func (i CloudDbSystemMap) ToCloudDbSystemMapOutput() CloudDbSystemMapOutput {
	return i.ToCloudDbSystemMapOutputWithContext(context.Background())
}

func (i CloudDbSystemMap) ToCloudDbSystemMapOutputWithContext(ctx context.Context) CloudDbSystemMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CloudDbSystemMapOutput)
}

type CloudDbSystemOutput struct{ *pulumi.OutputState }

func (CloudDbSystemOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CloudDbSystem)(nil)).Elem()
}

func (o CloudDbSystemOutput) ToCloudDbSystemOutput() CloudDbSystemOutput {
	return o
}

func (o CloudDbSystemOutput) ToCloudDbSystemOutputWithContext(ctx context.Context) CloudDbSystemOutput {
	return o
}

// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment in which the cloud DB system resides.
func (o CloudDbSystemOutput) CompartmentId() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudDbSystem) pulumi.StringOutput { return v.CompartmentId }).(pulumi.StringOutput)
}

// The configuration details of Database Management for a cloud DB system.
func (o CloudDbSystemOutput) DatabaseManagementConfig() CloudDbSystemDatabaseManagementConfigOutput {
	return o.ApplyT(func(v *CloudDbSystem) CloudDbSystemDatabaseManagementConfigOutput { return v.DatabaseManagementConfig }).(CloudDbSystemDatabaseManagementConfigOutput)
}

// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the DB system discovery.
func (o CloudDbSystemOutput) DbSystemDiscoveryId() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudDbSystem) pulumi.StringOutput { return v.DbSystemDiscoveryId }).(pulumi.StringOutput)
}

// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the parent cloud DB Infrastructure. For VM Dbsystems , it will be the DBSystem Id. For ExaCS and ExaCC,  it will be the cloudVmClusterId and vmClusterId respectively.
func (o CloudDbSystemOutput) DbaasParentInfrastructureId() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudDbSystem) pulumi.StringOutput { return v.DbaasParentInfrastructureId }).(pulumi.StringOutput)
}

// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see [Resource Tags](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm). Example: `{"Operations.CostCenter": "42"}`
func (o CloudDbSystemOutput) DefinedTags() pulumi.StringMapOutput {
	return o.ApplyT(func(v *CloudDbSystem) pulumi.StringMapOutput { return v.DefinedTags }).(pulumi.StringMapOutput)
}

// The deployment type of cloud dbsystem.
func (o CloudDbSystemOutput) DeploymentType() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudDbSystem) pulumi.StringOutput { return v.DeploymentType }).(pulumi.StringOutput)
}

// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the management agent used during the discovery of the DB system.
func (o CloudDbSystemOutput) DiscoveryAgentId() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudDbSystem) pulumi.StringOutput { return v.DiscoveryAgentId }).(pulumi.StringOutput)
}

// (Updatable) The user-friendly name for the DB system. The name does not have to be unique.
func (o CloudDbSystemOutput) DisplayName() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudDbSystem) pulumi.StringOutput { return v.DisplayName }).(pulumi.StringOutput)
}

// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see [Resource Tags](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm). Example: `{"Department": "Finance"}`
func (o CloudDbSystemOutput) FreeformTags() pulumi.StringMapOutput {
	return o.ApplyT(func(v *CloudDbSystem) pulumi.StringMapOutput { return v.FreeformTags }).(pulumi.StringMapOutput)
}

// The Oracle Grid home directory in case of cluster-based DB system and Oracle home directory in case of single instance-based DB system.
func (o CloudDbSystemOutput) HomeDirectory() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudDbSystem) pulumi.StringOutput { return v.HomeDirectory }).(pulumi.StringOutput)
}

// Indicates whether the DB system is a cluster DB system or not.
func (o CloudDbSystemOutput) IsCluster() pulumi.BoolOutput {
	return o.ApplyT(func(v *CloudDbSystem) pulumi.BoolOutput { return v.IsCluster }).(pulumi.BoolOutput)
}

// Additional information about the current lifecycle state.
func (o CloudDbSystemOutput) LifecycleDetails() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudDbSystem) pulumi.StringOutput { return v.LifecycleDetails }).(pulumi.StringOutput)
}

// The configuration details of Stack Monitoring for a cloud DB system.
func (o CloudDbSystemOutput) StackMonitoringConfig() CloudDbSystemStackMonitoringConfigOutput {
	return o.ApplyT(func(v *CloudDbSystem) CloudDbSystemStackMonitoringConfigOutput { return v.StackMonitoringConfig }).(CloudDbSystemStackMonitoringConfigOutput)
}

// The current lifecycle state of the cloud DB system resource.
func (o CloudDbSystemOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudDbSystem) pulumi.StringOutput { return v.State }).(pulumi.StringOutput)
}

// System tags for this resource. Each key is predefined and scoped to a namespace. For more information, see [Resource Tags](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/resourcetags.htm). System tags can be viewed by users, but can only be created by the system.  Example: `{"orcl-cloud.free-tier-retained": "true"}`
func (o CloudDbSystemOutput) SystemTags() pulumi.StringMapOutput {
	return o.ApplyT(func(v *CloudDbSystem) pulumi.StringMapOutput { return v.SystemTags }).(pulumi.StringMapOutput)
}

// The date and time the cloud DB system was created.
func (o CloudDbSystemOutput) TimeCreated() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudDbSystem) pulumi.StringOutput { return v.TimeCreated }).(pulumi.StringOutput)
}

// The date and time the cloud DB system was last updated.
func (o CloudDbSystemOutput) TimeUpdated() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudDbSystem) pulumi.StringOutput { return v.TimeUpdated }).(pulumi.StringOutput)
}

type CloudDbSystemArrayOutput struct{ *pulumi.OutputState }

func (CloudDbSystemArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CloudDbSystem)(nil)).Elem()
}

func (o CloudDbSystemArrayOutput) ToCloudDbSystemArrayOutput() CloudDbSystemArrayOutput {
	return o
}

func (o CloudDbSystemArrayOutput) ToCloudDbSystemArrayOutputWithContext(ctx context.Context) CloudDbSystemArrayOutput {
	return o
}

func (o CloudDbSystemArrayOutput) Index(i pulumi.IntInput) CloudDbSystemOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *CloudDbSystem {
		return vs[0].([]*CloudDbSystem)[vs[1].(int)]
	}).(CloudDbSystemOutput)
}

type CloudDbSystemMapOutput struct{ *pulumi.OutputState }

func (CloudDbSystemMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CloudDbSystem)(nil)).Elem()
}

func (o CloudDbSystemMapOutput) ToCloudDbSystemMapOutput() CloudDbSystemMapOutput {
	return o
}

func (o CloudDbSystemMapOutput) ToCloudDbSystemMapOutputWithContext(ctx context.Context) CloudDbSystemMapOutput {
	return o
}

func (o CloudDbSystemMapOutput) MapIndex(k pulumi.StringInput) CloudDbSystemOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *CloudDbSystem {
		return vs[0].(map[string]*CloudDbSystem)[vs[1].(string)]
	}).(CloudDbSystemOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CloudDbSystemInput)(nil)).Elem(), &CloudDbSystem{})
	pulumi.RegisterInputType(reflect.TypeOf((*CloudDbSystemArrayInput)(nil)).Elem(), CloudDbSystemArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*CloudDbSystemMapInput)(nil)).Elem(), CloudDbSystemMap{})
	pulumi.RegisterOutputType(CloudDbSystemOutput{})
	pulumi.RegisterOutputType(CloudDbSystemArrayOutput{})
	pulumi.RegisterOutputType(CloudDbSystemMapOutput{})
}
