// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * This data source provides details about a specific Security Assessment Template Baseline Comparison resource in Oracle Cloud Infrastructure Data Safe service.
 *
 * Gets the details of the comparison report for the security assessments submitted for comparison.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as oci from "@pulumi/oci";
 *
 * const testSecurityAssessmentTemplateBaselineComparison = oci.DataSafe.getSecurityAssessmentTemplateBaselineComparison({
 *     comparisonSecurityAssessmentId: testSecurityAssessment.id,
 *     securityAssessmentId: testSecurityAssessment.id,
 *     category: securityAssessmentTemplateBaselineComparisonCategory,
 *     findingKey: securityAssessmentTemplateBaselineComparisonFindingKey,
 *     targetId: testTarget.id,
 * });
 * ```
 */
export function getSecurityAssessmentTemplateBaselineComparison(args: GetSecurityAssessmentTemplateBaselineComparisonArgs, opts?: pulumi.InvokeOptions): Promise<GetSecurityAssessmentTemplateBaselineComparisonResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("oci:DataSafe/getSecurityAssessmentTemplateBaselineComparison:getSecurityAssessmentTemplateBaselineComparison", {
        "category": args.category,
        "comparisonSecurityAssessmentId": args.comparisonSecurityAssessmentId,
        "findingKey": args.findingKey,
        "securityAssessmentId": args.securityAssessmentId,
        "targetId": args.targetId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSecurityAssessmentTemplateBaselineComparison.
 */
export interface GetSecurityAssessmentTemplateBaselineComparisonArgs {
    /**
     * The category of the finding.
     */
    category?: string;
    /**
     * The OCID of the security assessment baseline.
     */
    comparisonSecurityAssessmentId: string;
    /**
     * The unique key that identifies the finding. It is a string and unique within a security assessment.
     */
    findingKey?: string;
    /**
     * The OCID of the security assessment.
     */
    securityAssessmentId: string;
    /**
     * A filter to return only items related to a specific target OCID.
     */
    targetId?: string;
}

/**
 * A collection of values returned by getSecurityAssessmentTemplateBaselineComparison.
 */
export interface GetSecurityAssessmentTemplateBaselineComparisonResult {
    /**
     * A comparison between findings belonging to Auditing category.
     */
    readonly auditings: outputs.DataSafe.GetSecurityAssessmentTemplateBaselineComparisonAuditing[];
    /**
     * A comparison between findings belonging to Authorization Control category.
     */
    readonly authorizationControls: outputs.DataSafe.GetSecurityAssessmentTemplateBaselineComparisonAuthorizationControl[];
    readonly category?: string;
    readonly comparisonSecurityAssessmentId: string;
    /**
     * Comparison between findings belonging to Data Encryption category.
     */
    readonly dataEncryptions: outputs.DataSafe.GetSecurityAssessmentTemplateBaselineComparisonDataEncryption[];
    /**
     * Comparison between findings belonging to Database Configuration category.
     */
    readonly dbConfigurations: outputs.DataSafe.GetSecurityAssessmentTemplateBaselineComparisonDbConfiguration[];
    readonly findingKey?: string;
    /**
     * Comparison between findings belonging to Fine-Grained Access Control category.
     */
    readonly fineGrainedAccessControls: outputs.DataSafe.GetSecurityAssessmentTemplateBaselineComparisonFineGrainedAccessControl[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * Comparison between findings belonging to Privileges and Roles category.
     */
    readonly privilegesAndRoles: outputs.DataSafe.GetSecurityAssessmentTemplateBaselineComparisonPrivilegesAndRole[];
    readonly securityAssessmentId: string;
    /**
     * The current state of the finding.
     */
    readonly state: string;
    /**
     * The OCID of the target database.
     */
    readonly targetId?: string;
    /**
     * The OCID of the security assessment that is set as a template baseline.
     */
    readonly templateBaselineId: string;
    /**
     * The display name of the security assessment that is set as a template baseline.
     */
    readonly templateBaselineName: string;
    /**
     * The date and time when the security assessment comparison was created. Conforms to the format defined by [RFC3339](https://tools.ietf.org/html/rfc3339).
     */
    readonly timeCreated: string;
    /**
     * Comparison between findings belonging to User Accounts category.
     */
    readonly userAccounts: outputs.DataSafe.GetSecurityAssessmentTemplateBaselineComparisonUserAccount[];
}
/**
 * This data source provides details about a specific Security Assessment Template Baseline Comparison resource in Oracle Cloud Infrastructure Data Safe service.
 *
 * Gets the details of the comparison report for the security assessments submitted for comparison.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as oci from "@pulumi/oci";
 *
 * const testSecurityAssessmentTemplateBaselineComparison = oci.DataSafe.getSecurityAssessmentTemplateBaselineComparison({
 *     comparisonSecurityAssessmentId: testSecurityAssessment.id,
 *     securityAssessmentId: testSecurityAssessment.id,
 *     category: securityAssessmentTemplateBaselineComparisonCategory,
 *     findingKey: securityAssessmentTemplateBaselineComparisonFindingKey,
 *     targetId: testTarget.id,
 * });
 * ```
 */
export function getSecurityAssessmentTemplateBaselineComparisonOutput(args: GetSecurityAssessmentTemplateBaselineComparisonOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSecurityAssessmentTemplateBaselineComparisonResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("oci:DataSafe/getSecurityAssessmentTemplateBaselineComparison:getSecurityAssessmentTemplateBaselineComparison", {
        "category": args.category,
        "comparisonSecurityAssessmentId": args.comparisonSecurityAssessmentId,
        "findingKey": args.findingKey,
        "securityAssessmentId": args.securityAssessmentId,
        "targetId": args.targetId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSecurityAssessmentTemplateBaselineComparison.
 */
export interface GetSecurityAssessmentTemplateBaselineComparisonOutputArgs {
    /**
     * The category of the finding.
     */
    category?: pulumi.Input<string>;
    /**
     * The OCID of the security assessment baseline.
     */
    comparisonSecurityAssessmentId: pulumi.Input<string>;
    /**
     * The unique key that identifies the finding. It is a string and unique within a security assessment.
     */
    findingKey?: pulumi.Input<string>;
    /**
     * The OCID of the security assessment.
     */
    securityAssessmentId: pulumi.Input<string>;
    /**
     * A filter to return only items related to a specific target OCID.
     */
    targetId?: pulumi.Input<string>;
}
