// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.oci.oci.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Map;
import java.util.Objects;

@CustomType
public final class GetPsaPsaWorkRequestResource {
    /**
     * @return The way in which this resource is affected by the operation tracked in the work request. A resource being created, updated, or deleted remains in the IN_PROGRESS state until work is complete for that resource, at which point it transitions to CREATED, UPDATED, or DELETED, respectively.
     * 
     */
    private String actionType;
    /**
     * @return The resource type that the work request affects.
     * 
     */
    private String entityType;
    /**
     * @return The URI path that you can use for a GET request to access the resource metadata.
     * 
     */
    private String entityUri;
    /**
     * @return An [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) or other unique identifier for the resource.
     * 
     */
    private String identifier;
    /**
     * @return Additional information that helps to explain the resource.
     * 
     */
    private Map<String,String> metadata;

    private GetPsaPsaWorkRequestResource() {}
    /**
     * @return The way in which this resource is affected by the operation tracked in the work request. A resource being created, updated, or deleted remains in the IN_PROGRESS state until work is complete for that resource, at which point it transitions to CREATED, UPDATED, or DELETED, respectively.
     * 
     */
    public String actionType() {
        return this.actionType;
    }
    /**
     * @return The resource type that the work request affects.
     * 
     */
    public String entityType() {
        return this.entityType;
    }
    /**
     * @return The URI path that you can use for a GET request to access the resource metadata.
     * 
     */
    public String entityUri() {
        return this.entityUri;
    }
    /**
     * @return An [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) or other unique identifier for the resource.
     * 
     */
    public String identifier() {
        return this.identifier;
    }
    /**
     * @return Additional information that helps to explain the resource.
     * 
     */
    public Map<String,String> metadata() {
        return this.metadata;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetPsaPsaWorkRequestResource defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String actionType;
        private String entityType;
        private String entityUri;
        private String identifier;
        private Map<String,String> metadata;
        public Builder() {}
        public Builder(GetPsaPsaWorkRequestResource defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.actionType = defaults.actionType;
    	      this.entityType = defaults.entityType;
    	      this.entityUri = defaults.entityUri;
    	      this.identifier = defaults.identifier;
    	      this.metadata = defaults.metadata;
        }

        @CustomType.Setter
        public Builder actionType(String actionType) {
            if (actionType == null) {
              throw new MissingRequiredPropertyException("GetPsaPsaWorkRequestResource", "actionType");
            }
            this.actionType = actionType;
            return this;
        }
        @CustomType.Setter
        public Builder entityType(String entityType) {
            if (entityType == null) {
              throw new MissingRequiredPropertyException("GetPsaPsaWorkRequestResource", "entityType");
            }
            this.entityType = entityType;
            return this;
        }
        @CustomType.Setter
        public Builder entityUri(String entityUri) {
            if (entityUri == null) {
              throw new MissingRequiredPropertyException("GetPsaPsaWorkRequestResource", "entityUri");
            }
            this.entityUri = entityUri;
            return this;
        }
        @CustomType.Setter
        public Builder identifier(String identifier) {
            if (identifier == null) {
              throw new MissingRequiredPropertyException("GetPsaPsaWorkRequestResource", "identifier");
            }
            this.identifier = identifier;
            return this;
        }
        @CustomType.Setter
        public Builder metadata(Map<String,String> metadata) {
            if (metadata == null) {
              throw new MissingRequiredPropertyException("GetPsaPsaWorkRequestResource", "metadata");
            }
            this.metadata = metadata;
            return this;
        }
        public GetPsaPsaWorkRequestResource build() {
            final var _resultValue = new GetPsaPsaWorkRequestResource();
            _resultValue.actionType = actionType;
            _resultValue.entityType = entityType;
            _resultValue.entityUri = entityUri;
            _resultValue.identifier = identifier;
            _resultValue.metadata = metadata;
            return _resultValue;
        }
    }
}
