// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.oci.oci.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.oci.oci.outputs.GetPsaPsaWorkRequestsWorkRequestSummaryCollectionItem;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetPsaPsaWorkRequestsWorkRequestSummaryCollection {
    private List<GetPsaPsaWorkRequestsWorkRequestSummaryCollectionItem> items;

    private GetPsaPsaWorkRequestsWorkRequestSummaryCollection() {}
    public List<GetPsaPsaWorkRequestsWorkRequestSummaryCollectionItem> items() {
        return this.items;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetPsaPsaWorkRequestsWorkRequestSummaryCollection defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<GetPsaPsaWorkRequestsWorkRequestSummaryCollectionItem> items;
        public Builder() {}
        public Builder(GetPsaPsaWorkRequestsWorkRequestSummaryCollection defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.items = defaults.items;
        }

        @CustomType.Setter
        public Builder items(List<GetPsaPsaWorkRequestsWorkRequestSummaryCollectionItem> items) {
            if (items == null) {
              throw new MissingRequiredPropertyException("GetPsaPsaWorkRequestsWorkRequestSummaryCollection", "items");
            }
            this.items = items;
            return this;
        }
        public Builder items(GetPsaPsaWorkRequestsWorkRequestSummaryCollectionItem... items) {
            return items(List.of(items));
        }
        public GetPsaPsaWorkRequestsWorkRequestSummaryCollection build() {
            final var _resultValue = new GetPsaPsaWorkRequestsWorkRequestSummaryCollection();
            _resultValue.items = items;
            return _resultValue;
        }
    }
}
