// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.oci.Sch.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetServiceConnectorTaskPrivateEndpointMetadata {
    /**
     * @return The reverse connection endpoint (RCE) IP address for DNS lookups.
     * 
     */
    private String rceDnsProxyIpAddress;
    /**
     * @return The reverse connection endpoint (RCE) IP address for primary flow of traffic in the subnet.
     * 
     */
    private String rceTrafficIpAddress;

    private GetServiceConnectorTaskPrivateEndpointMetadata() {}
    /**
     * @return The reverse connection endpoint (RCE) IP address for DNS lookups.
     * 
     */
    public String rceDnsProxyIpAddress() {
        return this.rceDnsProxyIpAddress;
    }
    /**
     * @return The reverse connection endpoint (RCE) IP address for primary flow of traffic in the subnet.
     * 
     */
    public String rceTrafficIpAddress() {
        return this.rceTrafficIpAddress;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetServiceConnectorTaskPrivateEndpointMetadata defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String rceDnsProxyIpAddress;
        private String rceTrafficIpAddress;
        public Builder() {}
        public Builder(GetServiceConnectorTaskPrivateEndpointMetadata defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.rceDnsProxyIpAddress = defaults.rceDnsProxyIpAddress;
    	      this.rceTrafficIpAddress = defaults.rceTrafficIpAddress;
        }

        @CustomType.Setter
        public Builder rceDnsProxyIpAddress(String rceDnsProxyIpAddress) {
            if (rceDnsProxyIpAddress == null) {
              throw new MissingRequiredPropertyException("GetServiceConnectorTaskPrivateEndpointMetadata", "rceDnsProxyIpAddress");
            }
            this.rceDnsProxyIpAddress = rceDnsProxyIpAddress;
            return this;
        }
        @CustomType.Setter
        public Builder rceTrafficIpAddress(String rceTrafficIpAddress) {
            if (rceTrafficIpAddress == null) {
              throw new MissingRequiredPropertyException("GetServiceConnectorTaskPrivateEndpointMetadata", "rceTrafficIpAddress");
            }
            this.rceTrafficIpAddress = rceTrafficIpAddress;
            return this;
        }
        public GetServiceConnectorTaskPrivateEndpointMetadata build() {
            final var _resultValue = new GetServiceConnectorTaskPrivateEndpointMetadata();
            _resultValue.rceDnsProxyIpAddress = rceDnsProxyIpAddress;
            _resultValue.rceTrafficIpAddress = rceTrafficIpAddress;
            return _resultValue;
        }
    }
}
