// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.oci.Sch.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.oci.Sch.outputs.GetServiceConnectorSourceMonitoringSourceNamespaceDetail;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetServiceConnectorSourceMonitoringSource {
    /**
     * @return The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment containing the metric.
     * 
     */
    private final String compartmentId;
    /**
     * @return Discriminator for namespaces in the compartment-specific list.
     * 
     */
    private final List<GetServiceConnectorSourceMonitoringSourceNamespaceDetail> namespaceDetails;

    @CustomType.Constructor
    private GetServiceConnectorSourceMonitoringSource(
        @CustomType.Parameter("compartmentId") String compartmentId,
        @CustomType.Parameter("namespaceDetails") List<GetServiceConnectorSourceMonitoringSourceNamespaceDetail> namespaceDetails) {
        this.compartmentId = compartmentId;
        this.namespaceDetails = namespaceDetails;
    }

    /**
     * @return The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment containing the metric.
     * 
     */
    public String compartmentId() {
        return this.compartmentId;
    }
    /**
     * @return Discriminator for namespaces in the compartment-specific list.
     * 
     */
    public List<GetServiceConnectorSourceMonitoringSourceNamespaceDetail> namespaceDetails() {
        return this.namespaceDetails;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetServiceConnectorSourceMonitoringSource defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private String compartmentId;
        private List<GetServiceConnectorSourceMonitoringSourceNamespaceDetail> namespaceDetails;

        public Builder() {
    	      // Empty
        }

        public Builder(GetServiceConnectorSourceMonitoringSource defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.compartmentId = defaults.compartmentId;
    	      this.namespaceDetails = defaults.namespaceDetails;
        }

        public Builder compartmentId(String compartmentId) {
            this.compartmentId = Objects.requireNonNull(compartmentId);
            return this;
        }
        public Builder namespaceDetails(List<GetServiceConnectorSourceMonitoringSourceNamespaceDetail> namespaceDetails) {
            this.namespaceDetails = Objects.requireNonNull(namespaceDetails);
            return this;
        }
        public Builder namespaceDetails(GetServiceConnectorSourceMonitoringSourceNamespaceDetail... namespaceDetails) {
            return namespaceDetails(List.of(namespaceDetails));
        }        public GetServiceConnectorSourceMonitoringSource build() {
            return new GetServiceConnectorSourceMonitoringSource(compartmentId, namespaceDetails);
        }
    }
}
