// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Oci.Oci.Inputs
{

    public sealed class DataccInfrastructureSystemStorageCapacityAcfGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The total amount of logical disk space that is currently available for use, in gigabytes (GB).
        /// </summary>
        [Input("freeSpaceInGbs")]
        public Input<double>? FreeSpaceInGbs { get; set; }

        /// <summary>
        /// The total amount of logical disk space available, in gigabytes (GB).
        /// </summary>
        [Input("totalSpaceInGbs")]
        public Input<double>? TotalSpaceInGbs { get; set; }

        public DataccInfrastructureSystemStorageCapacityAcfGetArgs()
        {
        }
        public static new DataccInfrastructureSystemStorageCapacityAcfGetArgs Empty => new DataccInfrastructureSystemStorageCapacityAcfGetArgs();
    }
}
