// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Oci.OspGateway.Outputs
{

    [OutputType]
    public sealed class SubscriptionSubscriptionBillingAddress
    {
        /// <summary>
        /// (Updatable) Address identifier.
        /// </summary>
        public readonly string? AddressKey;
        /// <summary>
        /// (Updatable) Name of the city.
        /// </summary>
        public readonly string? City;
        /// <summary>
        /// (Updatable) Name of the customer company.
        /// </summary>
        public readonly string? CompanyName;
        /// <summary>
        /// (Updatable) Contributor class of the customer company.
        /// </summary>
        public readonly string? ContributorClass;
        /// <summary>
        /// (Updatable) Country of the address.
        /// </summary>
        public readonly string? Country;
        /// <summary>
        /// (Updatable) County of the address.
        /// </summary>
        public readonly string? County;
        /// <summary>
        /// (Updatable) Department name of the customer company.
        /// </summary>
        public readonly string? DepartmentName;
        /// <summary>
        /// (Updatable) Contact person email address.
        /// </summary>
        public readonly string? EmailAddress;
        /// <summary>
        /// (Updatable) First name of the contact person.
        /// </summary>
        public readonly string? FirstName;
        /// <summary>
        /// (Updatable) Internal number of the customer company.
        /// </summary>
        public readonly string? InternalNumber;
        /// <summary>
        /// (Updatable) Job title of the contact person.
        /// </summary>
        public readonly string? JobTitle;
        /// <summary>
        /// (Updatable) Last name of the contact person.
        /// </summary>
        public readonly string? LastName;
        /// <summary>
        /// (Updatable) Address line 1.
        /// </summary>
        public readonly string? Line1;
        /// <summary>
        /// (Updatable) Address line 2.
        /// </summary>
        public readonly string? Line2;
        /// <summary>
        /// (Updatable) Address line 3.
        /// </summary>
        public readonly string? Line3;
        /// <summary>
        /// (Updatable) Address line 4.
        /// </summary>
        public readonly string? Line4;
        /// <summary>
        /// (Updatable) Middle name of the contact person.
        /// </summary>
        public readonly string? MiddleName;
        /// <summary>
        /// (Updatable) Municipal Inscription.
        /// </summary>
        public readonly string? MunicipalInscription;
        /// <summary>
        /// (Updatable) Phone country code of the contact person.
        /// </summary>
        public readonly string? PhoneCountryCode;
        /// <summary>
        /// (Updatable) Phone number of the contact person.
        /// </summary>
        public readonly string? PhoneNumber;
        /// <summary>
        /// (Updatable) Post code of the address.
        /// </summary>
        public readonly string? PostalCode;
        /// <summary>
        /// (Updatable) Province of the address.
        /// </summary>
        public readonly string? Province;
        /// <summary>
        /// (Updatable) State of the address.
        /// </summary>
        public readonly string? State;
        /// <summary>
        /// (Updatable) State Inscription.
        /// </summary>
        public readonly string? StateInscription;
        /// <summary>
        /// (Updatable) Street name of the address.
        /// </summary>
        public readonly string? StreetName;
        /// <summary>
        /// (Updatable) Street number of the address.
        /// </summary>
        public readonly string? StreetNumber;

        [OutputConstructor]
        private SubscriptionSubscriptionBillingAddress(
            string? addressKey,

            string? city,

            string? companyName,

            string? contributorClass,

            string? country,

            string? county,

            string? departmentName,

            string? emailAddress,

            string? firstName,

            string? internalNumber,

            string? jobTitle,

            string? lastName,

            string? line1,

            string? line2,

            string? line3,

            string? line4,

            string? middleName,

            string? municipalInscription,

            string? phoneCountryCode,

            string? phoneNumber,

            string? postalCode,

            string? province,

            string? state,

            string? stateInscription,

            string? streetName,

            string? streetNumber)
        {
            AddressKey = addressKey;
            City = city;
            CompanyName = companyName;
            ContributorClass = contributorClass;
            Country = country;
            County = county;
            DepartmentName = departmentName;
            EmailAddress = emailAddress;
            FirstName = firstName;
            InternalNumber = internalNumber;
            JobTitle = jobTitle;
            LastName = lastName;
            Line1 = line1;
            Line2 = line2;
            Line3 = line3;
            Line4 = line4;
            MiddleName = middleName;
            MunicipalInscription = municipalInscription;
            PhoneCountryCode = phoneCountryCode;
            PhoneNumber = phoneNumber;
            PostalCode = postalCode;
            Province = province;
            State = state;
            StateInscription = stateInscription;
            StreetName = streetName;
            StreetNumber = streetNumber;
        }
    }
}
