// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Oci.OsManagementHub.Outputs
{

    [OutputType]
    public sealed class GetEntitlementsEntitlementCollectionResult
    {
        /// <summary>
        /// The [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment. This parameter is required and returns only resources contained within the specified compartment.
        /// </summary>
        public readonly string CompartmentId;
        /// <summary>
        /// A filter to return entitlements that match the given CSI.
        /// </summary>
        public readonly string Csi;
        /// <summary>
        /// List of entitlements.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetEntitlementsEntitlementCollectionItemResult> Items;

        [OutputConstructor]
        private GetEntitlementsEntitlementCollectionResult(
            string compartmentId,

            string csi,

            ImmutableArray<Outputs.GetEntitlementsEntitlementCollectionItemResult> items)
        {
            CompartmentId = compartmentId;
            Csi = csi;
            Items = items;
        }
    }
}
