// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.oci.ApiGateway.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.oci.ApiGateway.outputs.GetApiDeploymentSpecificationRouteRequestPolicyQueryParameterValidationParameter;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetApiDeploymentSpecificationRouteRequestPolicyQueryParameterValidation {
    private @Nullable List<GetApiDeploymentSpecificationRouteRequestPolicyQueryParameterValidationParameter> parameters;
    /**
     * @return Validation behavior mode.
     * 
     */
    private @Nullable String validationMode;

    private GetApiDeploymentSpecificationRouteRequestPolicyQueryParameterValidation() {}
    public List<GetApiDeploymentSpecificationRouteRequestPolicyQueryParameterValidationParameter> parameters() {
        return this.parameters == null ? List.of() : this.parameters;
    }
    /**
     * @return Validation behavior mode.
     * 
     */
    public Optional<String> validationMode() {
        return Optional.ofNullable(this.validationMode);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetApiDeploymentSpecificationRouteRequestPolicyQueryParameterValidation defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<GetApiDeploymentSpecificationRouteRequestPolicyQueryParameterValidationParameter> parameters;
        private @Nullable String validationMode;
        public Builder() {}
        public Builder(GetApiDeploymentSpecificationRouteRequestPolicyQueryParameterValidation defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.parameters = defaults.parameters;
    	      this.validationMode = defaults.validationMode;
        }

        @CustomType.Setter
        public Builder parameters(@Nullable List<GetApiDeploymentSpecificationRouteRequestPolicyQueryParameterValidationParameter> parameters) {
            this.parameters = parameters;
            return this;
        }
        public Builder parameters(GetApiDeploymentSpecificationRouteRequestPolicyQueryParameterValidationParameter... parameters) {
            return parameters(List.of(parameters));
        }
        @CustomType.Setter
        public Builder validationMode(@Nullable String validationMode) {
            this.validationMode = validationMode;
            return this;
        }
        public GetApiDeploymentSpecificationRouteRequestPolicyQueryParameterValidation build() {
            final var o = new GetApiDeploymentSpecificationRouteRequestPolicyQueryParameterValidation();
            o.parameters = parameters;
            o.validationMode = validationMode;
            return o;
        }
    }
}
