// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.oci.ComputeCloud.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetAtCustomerCccInfrastructurePlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetAtCustomerCccInfrastructurePlainArgs Empty = new GetAtCustomerCccInfrastructurePlainArgs();

    /**
     * An [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) for a  Compute Cloud{@literal @}Customer Infrastructure.
     * 
     */
    @Import(name="cccInfrastructureId", required=true)
    private String cccInfrastructureId;

    /**
     * @return An [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) for a  Compute Cloud{@literal @}Customer Infrastructure.
     * 
     */
    public String cccInfrastructureId() {
        return this.cccInfrastructureId;
    }

    private GetAtCustomerCccInfrastructurePlainArgs() {}

    private GetAtCustomerCccInfrastructurePlainArgs(GetAtCustomerCccInfrastructurePlainArgs $) {
        this.cccInfrastructureId = $.cccInfrastructureId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetAtCustomerCccInfrastructurePlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetAtCustomerCccInfrastructurePlainArgs $;

        public Builder() {
            $ = new GetAtCustomerCccInfrastructurePlainArgs();
        }

        public Builder(GetAtCustomerCccInfrastructurePlainArgs defaults) {
            $ = new GetAtCustomerCccInfrastructurePlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param cccInfrastructureId An [OCID](https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) for a  Compute Cloud{@literal @}Customer Infrastructure.
         * 
         * @return builder
         * 
         */
        public Builder cccInfrastructureId(String cccInfrastructureId) {
            $.cccInfrastructureId = cccInfrastructureId;
            return this;
        }

        public GetAtCustomerCccInfrastructurePlainArgs build() {
            if ($.cccInfrastructureId == null) {
                throw new MissingRequiredPropertyException("GetAtCustomerCccInfrastructurePlainArgs", "cccInfrastructureId");
            }
            return $;
        }
    }

}
