// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Oci.ContainerEngine.Inputs
{

    public sealed class ContainerInstanceVolumeConfigArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The base64 encoded contents of the file. The contents are decoded to plain text before mounted as a file to a container inside container instance.
        /// </summary>
        [Input("data")]
        public Input<string>? Data { get; set; }

        /// <summary>
        /// The name of the file. The fileName should be unique across the volume.
        /// </summary>
        [Input("fileName")]
        public Input<string>? FileName { get; set; }

        /// <summary>
        /// (Optional) Relative path for this file inside the volume mount directory. By default, the file is presented at the root of the volume mount path.
        /// </summary>
        [Input("path")]
        public Input<string>? Path { get; set; }

        public ContainerInstanceVolumeConfigArgs()
        {
        }
        public static new ContainerInstanceVolumeConfigArgs Empty => new ContainerInstanceVolumeConfigArgs();
    }
}
