// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.oci.DataSafe.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.oci.DataSafe.outputs.GetMaskingReportsMaskingReportCollectionItem;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetMaskingReportsMaskingReportCollection {
    private List<GetMaskingReportsMaskingReportCollectionItem> items;

    private GetMaskingReportsMaskingReportCollection() {}
    public List<GetMaskingReportsMaskingReportCollectionItem> items() {
        return this.items;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetMaskingReportsMaskingReportCollection defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<GetMaskingReportsMaskingReportCollectionItem> items;
        public Builder() {}
        public Builder(GetMaskingReportsMaskingReportCollection defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.items = defaults.items;
        }

        @CustomType.Setter
        public Builder items(List<GetMaskingReportsMaskingReportCollectionItem> items) {
            this.items = Objects.requireNonNull(items);
            return this;
        }
        public Builder items(GetMaskingReportsMaskingReportCollectionItem... items) {
            return items(List.of(items));
        }
        public GetMaskingReportsMaskingReportCollection build() {
            final var o = new GetMaskingReportsMaskingReportCollection();
            o.items = items;
            return o;
        }
    }
}
