// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.oci.DataSafe.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.util.Objects;

@CustomType
public final class GetSecurityAssessmentStatisticAdvisory {
    /**
     * @return The number of findings in the Auditing category.
     * 
     */
    private Integer auditingFindingsCount;
    /**
     * @return The number of findings in the Authorization Control category.
     * 
     */
    private Integer authorizationControlFindingsCount;
    /**
     * @return The number of findings in the Data Encryption category.
     * 
     */
    private Integer dataEncryptionFindingsCount;
    /**
     * @return The number of findings in the Database Configuration category.
     * 
     */
    private Integer dbConfigurationFindingsCount;
    /**
     * @return The number of findings in the Fine-Grained Access Control category.
     * 
     */
    private Integer fineGrainedAccessControlFindingsCount;
    /**
     * @return The number of findings in the Privileges and Roles category.
     * 
     */
    private Integer privilegesAndRolesFindingsCount;
    /**
     * @return The total number of targets in this security assessment.
     * 
     */
    private Integer targetsCount;
    /**
     * @return The number of findings in the User Accounts category.
     * 
     */
    private Integer userAccountsFindingsCount;

    private GetSecurityAssessmentStatisticAdvisory() {}
    /**
     * @return The number of findings in the Auditing category.
     * 
     */
    public Integer auditingFindingsCount() {
        return this.auditingFindingsCount;
    }
    /**
     * @return The number of findings in the Authorization Control category.
     * 
     */
    public Integer authorizationControlFindingsCount() {
        return this.authorizationControlFindingsCount;
    }
    /**
     * @return The number of findings in the Data Encryption category.
     * 
     */
    public Integer dataEncryptionFindingsCount() {
        return this.dataEncryptionFindingsCount;
    }
    /**
     * @return The number of findings in the Database Configuration category.
     * 
     */
    public Integer dbConfigurationFindingsCount() {
        return this.dbConfigurationFindingsCount;
    }
    /**
     * @return The number of findings in the Fine-Grained Access Control category.
     * 
     */
    public Integer fineGrainedAccessControlFindingsCount() {
        return this.fineGrainedAccessControlFindingsCount;
    }
    /**
     * @return The number of findings in the Privileges and Roles category.
     * 
     */
    public Integer privilegesAndRolesFindingsCount() {
        return this.privilegesAndRolesFindingsCount;
    }
    /**
     * @return The total number of targets in this security assessment.
     * 
     */
    public Integer targetsCount() {
        return this.targetsCount;
    }
    /**
     * @return The number of findings in the User Accounts category.
     * 
     */
    public Integer userAccountsFindingsCount() {
        return this.userAccountsFindingsCount;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetSecurityAssessmentStatisticAdvisory defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Integer auditingFindingsCount;
        private Integer authorizationControlFindingsCount;
        private Integer dataEncryptionFindingsCount;
        private Integer dbConfigurationFindingsCount;
        private Integer fineGrainedAccessControlFindingsCount;
        private Integer privilegesAndRolesFindingsCount;
        private Integer targetsCount;
        private Integer userAccountsFindingsCount;
        public Builder() {}
        public Builder(GetSecurityAssessmentStatisticAdvisory defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.auditingFindingsCount = defaults.auditingFindingsCount;
    	      this.authorizationControlFindingsCount = defaults.authorizationControlFindingsCount;
    	      this.dataEncryptionFindingsCount = defaults.dataEncryptionFindingsCount;
    	      this.dbConfigurationFindingsCount = defaults.dbConfigurationFindingsCount;
    	      this.fineGrainedAccessControlFindingsCount = defaults.fineGrainedAccessControlFindingsCount;
    	      this.privilegesAndRolesFindingsCount = defaults.privilegesAndRolesFindingsCount;
    	      this.targetsCount = defaults.targetsCount;
    	      this.userAccountsFindingsCount = defaults.userAccountsFindingsCount;
        }

        @CustomType.Setter
        public Builder auditingFindingsCount(Integer auditingFindingsCount) {
            if (auditingFindingsCount == null) {
              throw new MissingRequiredPropertyException("GetSecurityAssessmentStatisticAdvisory", "auditingFindingsCount");
            }
            this.auditingFindingsCount = auditingFindingsCount;
            return this;
        }
        @CustomType.Setter
        public Builder authorizationControlFindingsCount(Integer authorizationControlFindingsCount) {
            if (authorizationControlFindingsCount == null) {
              throw new MissingRequiredPropertyException("GetSecurityAssessmentStatisticAdvisory", "authorizationControlFindingsCount");
            }
            this.authorizationControlFindingsCount = authorizationControlFindingsCount;
            return this;
        }
        @CustomType.Setter
        public Builder dataEncryptionFindingsCount(Integer dataEncryptionFindingsCount) {
            if (dataEncryptionFindingsCount == null) {
              throw new MissingRequiredPropertyException("GetSecurityAssessmentStatisticAdvisory", "dataEncryptionFindingsCount");
            }
            this.dataEncryptionFindingsCount = dataEncryptionFindingsCount;
            return this;
        }
        @CustomType.Setter
        public Builder dbConfigurationFindingsCount(Integer dbConfigurationFindingsCount) {
            if (dbConfigurationFindingsCount == null) {
              throw new MissingRequiredPropertyException("GetSecurityAssessmentStatisticAdvisory", "dbConfigurationFindingsCount");
            }
            this.dbConfigurationFindingsCount = dbConfigurationFindingsCount;
            return this;
        }
        @CustomType.Setter
        public Builder fineGrainedAccessControlFindingsCount(Integer fineGrainedAccessControlFindingsCount) {
            if (fineGrainedAccessControlFindingsCount == null) {
              throw new MissingRequiredPropertyException("GetSecurityAssessmentStatisticAdvisory", "fineGrainedAccessControlFindingsCount");
            }
            this.fineGrainedAccessControlFindingsCount = fineGrainedAccessControlFindingsCount;
            return this;
        }
        @CustomType.Setter
        public Builder privilegesAndRolesFindingsCount(Integer privilegesAndRolesFindingsCount) {
            if (privilegesAndRolesFindingsCount == null) {
              throw new MissingRequiredPropertyException("GetSecurityAssessmentStatisticAdvisory", "privilegesAndRolesFindingsCount");
            }
            this.privilegesAndRolesFindingsCount = privilegesAndRolesFindingsCount;
            return this;
        }
        @CustomType.Setter
        public Builder targetsCount(Integer targetsCount) {
            if (targetsCount == null) {
              throw new MissingRequiredPropertyException("GetSecurityAssessmentStatisticAdvisory", "targetsCount");
            }
            this.targetsCount = targetsCount;
            return this;
        }
        @CustomType.Setter
        public Builder userAccountsFindingsCount(Integer userAccountsFindingsCount) {
            if (userAccountsFindingsCount == null) {
              throw new MissingRequiredPropertyException("GetSecurityAssessmentStatisticAdvisory", "userAccountsFindingsCount");
            }
            this.userAccountsFindingsCount = userAccountsFindingsCount;
            return this;
        }
        public GetSecurityAssessmentStatisticAdvisory build() {
            final var _resultValue = new GetSecurityAssessmentStatisticAdvisory();
            _resultValue.auditingFindingsCount = auditingFindingsCount;
            _resultValue.authorizationControlFindingsCount = authorizationControlFindingsCount;
            _resultValue.dataEncryptionFindingsCount = dataEncryptionFindingsCount;
            _resultValue.dbConfigurationFindingsCount = dbConfigurationFindingsCount;
            _resultValue.fineGrainedAccessControlFindingsCount = fineGrainedAccessControlFindingsCount;
            _resultValue.privilegesAndRolesFindingsCount = privilegesAndRolesFindingsCount;
            _resultValue.targetsCount = targetsCount;
            _resultValue.userAccountsFindingsCount = userAccountsFindingsCount;
            return _resultValue;
        }
    }
}
