// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.oci.DataScience.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ModelDeploymentModelDeploymentSystemData {
    /**
     * @return This value is the current count of the model deployment instances.
     * 
     */
    private @Nullable Integer currentInstanceCount;
    /**
     * @return The infrastructure type of the model deployment.
     * 
     */
    private @Nullable String systemInfraType;

    private ModelDeploymentModelDeploymentSystemData() {}
    /**
     * @return This value is the current count of the model deployment instances.
     * 
     */
    public Optional<Integer> currentInstanceCount() {
        return Optional.ofNullable(this.currentInstanceCount);
    }
    /**
     * @return The infrastructure type of the model deployment.
     * 
     */
    public Optional<String> systemInfraType() {
        return Optional.ofNullable(this.systemInfraType);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ModelDeploymentModelDeploymentSystemData defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Integer currentInstanceCount;
        private @Nullable String systemInfraType;
        public Builder() {}
        public Builder(ModelDeploymentModelDeploymentSystemData defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.currentInstanceCount = defaults.currentInstanceCount;
    	      this.systemInfraType = defaults.systemInfraType;
        }

        @CustomType.Setter
        public Builder currentInstanceCount(@Nullable Integer currentInstanceCount) {

            this.currentInstanceCount = currentInstanceCount;
            return this;
        }
        @CustomType.Setter
        public Builder systemInfraType(@Nullable String systemInfraType) {

            this.systemInfraType = systemInfraType;
            return this;
        }
        public ModelDeploymentModelDeploymentSystemData build() {
            final var _resultValue = new ModelDeploymentModelDeploymentSystemData();
            _resultValue.currentInstanceCount = currentInstanceCount;
            _resultValue.systemInfraType = systemInfraType;
            return _resultValue;
        }
    }
}
